package io.constellationnetwork.node.shared.domain.nakamoto.sharding

import cats.Parallel
import cats.effect.Async
import cats.syntax.all._

import io.constellationnetwork.json.JsonSerializer
import io.constellationnetwork.node.shared.domain.nakamoto.ShardAssignment
import io.constellationnetwork.schema.address.Address
import io.constellationnetwork.schema.mpt.GlobalStateKey
import io.constellationnetwork.schema.sharding.{ShardCheckpoint, ShardId}
import io.constellationnetwork.security.Hasher
import io.constellationnetwork.security.hash.Hash
import io.constellationnetwork.security.hex.Hex
import io.constellationnetwork.security.mpt.MerklePatriciaTrie
import io.constellationnetwork.security.mpt.prover.MerklePatriciaSingleInclusionProver
import io.constellationnetwork.security.mpt.prover.attestation.MerklePatriciaInclusionProof
import io.constellationnetwork.security.mpt.verifier.MerklePatriciaInclusionVerifier
import io.constellationnetwork.security.signature.Signed

import derevo.circe.magnolia.{decoder, encoder}
import derevo.derive

/** Cross-shard MPT inclusion proof envelope — Slice 10 of `docs/nakamoto/HIERARCHICAL-SHARD-CHECKPOINTS-DESIGN.md` §8.5/§8.6.
  *
  * The on-wire shape carried between shard committees when shard X needs to verify a key against shard Y's MPT state (e.g.
  * `SpendActionValidator` referencing an `AllowSpend` whose source belongs to a metagraph assigned to a different shard). The envelope
  * packs:
  *
  *   - `shardCheckpointHash` — the canonical [[ShardCheckpoint]] hash this proof is anchored at. The consumer looks up this hash in gl0's
  *     last-finalized snapshot's `shardCheckpoints[shardId]` to find the trusted root (per §8.6 step 1).
  *   - `metagraphAddress` — the per-MG subtree the proof witnesses. The consumer cross-checks this matches the requested MG.
  *   - `perMgMptRoot` — the verifier root: lifted from the checkpoint's `derivedStateDelta.perMetagraphMptRoots[metagraphAddress]` (PIN-1,
  *     the COMPONENT-ADDRESSABLE per-MG MPT root = `GlobalStateConverter.currencySnapshotMgRoot` — the `rootHash` of the MG sub-trie over
  *     the fieldId-5 incremental + `infoSubFields` `Mg*` entries). Because it is a real MPT root (not the old flat `hash((inc, info))`
  *     pair), the consumer runs the standard `MerklePatriciaInclusionVerifier` against it and the `mptProof`'s witness chain actually
  *     hashes up to it (per §8.6 step 2).
  *   - `key` — the [[GlobalStateKey]] this proof addresses (carried as a structured value so the consumer can re-derive the canonical hex
  *     path independently — the same `GlobalStateKey.toHex` encoding the MG sub-trie is keyed by).
  *   - `value` — `Some(hex)` carrying hex-encoded value bytes for membership proofs (v1 supported), `None` reserved for future
  *     proof-of-absence (v2 — the underlying [[MerklePatriciaInclusionVerifier]] currently has no absence-witness support, so v1 only ships
  *     membership proofs and surfaces absence by [[ShardSubtreeProofService.generateProofForMetagraph]] returning `None`). The wire
  *     encoding uses [[Hex]] rather than raw `Array[Byte]` so the envelope has stable Circe + Eq instances — the verifier doesn't care
  *     about the value bytes (only the proof's leaf commitment matters structurally); this field is for the consumer to read the value once
  *     verification passes.
  *   - `mptProof` — the standard MPT inclusion proof (path + witness commitments) generated by `MerklePatriciaSingleInclusionProver` over
  *     the per-MG sub-trie (the trie whose `rootHash` IS `perMgMptRoot`).
  *
  * '''Greenfield rule''' (per `[[feedback-greenfield-no-wire-compat]]`): fresh envelope for the cross-shard read path. No compat ceremony.
  *
  * '''Wire-byte stability.''' Field order and field set here is part of the cross-shard protocol contract. Adding a field, reordering, or
  * wrapping in `Option` silently changes the derevo magnolia-derived Circe JSON. Bump the case class explicitly (`ShardSubtreeProofV2`) and
  * version the verifier branch — same frozen-shape discipline as [[io.constellationnetwork.schema.sharding.ShardCheckpoint]].
  */
@derive(encoder, decoder)
final case class ShardSubtreeProof(
  shardCheckpointHash: Hash,
  metagraphAddress: Address,
  perMgMptRoot: Hash,
  key: GlobalStateKey,
  value: Option[Hex],
  mptProof: MerklePatriciaInclusionProof
)

/** Cross-shard MPT inclusion proof service — Slice 10 of `docs/nakamoto/HIERARCHICAL-SHARD-CHECKPOINTS-DESIGN.md` §8.5.
  *
  * '''Scope''' (per slice 10 task spec):
  *   - Generate inclusion proofs scoped to a single shard's subtree (`generateProofForMetagraph`).
  *   - Verify proofs against a committee-signed shard checkpoint's per-MG MPT root (`verifyProof`).
  *
  * '''Reuse''' — both paths route through existing primitives, but BOTH are now rooted at the COMPONENT-ADDRESSABLE per-MG sub-trie
  * (PIN-1), NOT the global trie:
  *   - Generation: build the MG sub-trie from the SAME `GlobalStateConverter.currencySnapshotMgEntries` bytes the committed
  *     `perMetagraphMptRoots(mg)` root commits to (supplied via the `perMgEntriesFor` callback), then run
  *     `MerklePatriciaSingleInclusionProver` over it. The proof's witness chain therefore terminates at `perMgMptRoot`. (Previously this
  *     proved over the GLOBAL trie via `HistoricalMptProofService.proofAtBranch`, whose witness chain terminated at the global root — a
  *     layer mismatch the verifier could never reconcile against the per-MG root.)
  *   - Verification: [[MerklePatriciaInclusionVerifier]] — standard MPT verifier rooted at the per-MG sub-trie root from the shard
  *     checkpoint. Unchanged: now that `perMgMptRoot` is a real MPT root, the standard verifier confirms the single-leaf witness against it
  *     directly.
  *
  * '''What this slice does NOT do''':
  *   - Maintain a persistent per-shard subtree producer — the MG sub-trie is rebuilt on demand from the reconstructed per-MG state (cheap:
  *     one MG's entries, not the whole global trie). v2 may introduce persistent per-shard producers if rebuild-on-demand ceases to scale.
  *   - Proof-of-absence — the underlying `MerklePatriciaInclusionVerifier` has no absence-witness support; generate returns `None` for
  *     absent keys instead of fabricating an absence proof. v2 target.
  *   - Handle the cross-shard read protocol itself (§8.6 P2P request shape) — that's slice 11/14 wiring. This slice provides the
  *     prover/verifier primitives the wire path will call.
  *
  * '''Read-after-write staleness''' (per design doc §8.3): cross-shard reads see state up to one gl0 snapshot stale (~7s). The service
  * surfaces this naturally — proofs reference a specific checkpoint hash; the proof is consistent with that checkpoint's state. No special
  * handling in v1.
  *
  * '''Greenfield rule''' (per `[[feedback-greenfield-no-wire-compat]]`): fresh prover/verifier for the cross-shard read path. No compat
  * ceremony.
  *
  * '''HOCON rule''' (per `[[feedback-prefer-hocon-over-sysenv]]`): all knobs are constructor parameters; production wiring passes typed
  * `SharedConfig.nakamoto.sharding.*` values via the injected [[ShardAssignment]]. No `sys.env.get` anywhere.
  */
trait ShardSubtreeProofService[F[_]] {

  /** Generate an inclusion proof for `key` under `metagraphAddress`'s subtree, attributable to the shard `shardId`. Caller pre-computes
    * `shardId` (typically via [[ShardAssignment.shardIdFor]]); the service cross-checks that `shardId` does in fact own `metagraphAddress`
    * per the deterministic static assignment and returns `None` on mismatch.
    *
    * Returns:
    *   - `Some(proof)` when (a) the shard owns the MG per static assignment, (b) a current checkpoint exists for the shard (resolved via
    *     the constructor-supplied `lookupShardCheckpoint`), AND (c) the key resolves to a value in the underlying MPT (membership case).
    *   - `None` when ANY of (a), (b), (c) doesn't hold. The caller distinguishes "shard not active" from "key absent" via the absence of a
    *     checkpoint at the lookup callback (returned to the caller as part of the wire-level 404 vs 503 mapping in the HTTP route — see
    *     `ShardProofRoutes` for that mapping).
    */
  def generateProofForMetagraph(
    shardId: ShardId,
    metagraphAddress: Address,
    key: GlobalStateKey
  ): F[Option[ShardSubtreeProof]]

  /** Verify a proof against its claimed shard checkpoint's per-MG MPT root.
    *
    * Returns `true` iff ALL of the following hold:
    *   - The proof's `perMgMptRoot` matches the checkpoint's `derivedStateDelta.perMetagraphMptRoots[metagraphAddress]`.
    *   - The proof's `shardCheckpointHash` matches the supplied `shardCheckpoint`'s canonical hash (re-derived via `Hasher[F]` over
    *     `signingPreimage`).
    *   - The proof's `metagraphAddress` is owned by `shardCheckpoint.shardId` per the static assignment.
    *   - The standard `MerklePatriciaInclusionVerifier` accepts the proof against `perMgMptRoot`.
    *
    * Tampered value bytes are caught structurally: the proof's leaf commitment embeds `dataDigest = Hasher.hash(value)`, and the leaf's
    * outer digest is part of the witness chain. Changing the value without re-deriving `dataDigest` invalidates the leaf commitment, which
    * the verifier rejects. Changing the value AND `dataDigest` invalidates the witness chain upward.
    *
    * The verify path also requires the proof's `value` (the bytes the proof's leaf commits to) to match what the proof anchors at. The
    * caller supplies the value to verify alongside the proof — the service does NOT trust the `value` field embedded in the proof envelope
    * for the verify path (defence-in-depth: the receiver should compute / receive `value` independently and pass it here, matching the
    * typical pattern where the wire response is `{ value, proof }` and the consumer validates the proof commits to that value).
    */
  def verifyProof(
    shardCheckpoint: Signed[ShardCheckpoint],
    proof: ShardSubtreeProof
  ): F[Boolean]
}

object ShardSubtreeProofService {

  /** Lookup callback for the most recent committee-signed shard checkpoint for a given shard. The production wiring resolves this from the
    * per-shard `ShardChainStore` (Slice 5) — typically `chainStore.bestTip.map(_.signed)`. Decoupling via callback so this slice doesn't
    * pull `ShardChainStore` as a transitive dependency — that's slice 11/14 wiring.
    *
    * Returns `None` when the shard has no current checkpoint (bootstrap, paused shard, etc.) — the service maps that to "cannot generate
    * proof" and surfaces it to the HTTP layer as 404 / 503 per the route's response-code policy.
    */
  type ShardCheckpointLookup[F[_]] = ShardId => F[Option[Signed[ShardCheckpoint]]]

  /** Per-MG component-entry lookup — the hex-keyed MPT entry set whose `rootHash` IS `perMetagraphMptRoots(mg)` (PIN-1). Production wiring
    * builds this from gl0's `GlobalStateReader` (reconstruct the MG's `(incremental, info)` state) routed through
    * `GlobalStateConverter.currencySnapshotMgEntries` — the SAME byte source the committed root commits to. Returns `None` when the MG has
    * no reconstructible state at the serve anchor (never-seen / pre-genesis); the service maps that to "cannot generate proof".
    *
    * Decoupling via callback keeps this slice free of a `GlobalStateReader` / `GlobalStateConverter` transitive dependency and lets tests
    * supply the entry bytes directly. The KEY contract: these bytes MUST be exactly the bytes
    * `GlobalStateConverter.currencySnapshotMgEntries(mg -> state)` produced for the state the committee attested, so the rebuilt sub-trie's
    * `rootHash === perMetagraphMptRoots(mg)` (the generate path asserts this consistency before emitting a proof).
    */
  type PerMgEntriesLookup[F[_]] = Address => F[Option[Map[Hex, Array[Byte]]]]

  /** Construct a [[ShardSubtreeProofService]].
    *
    * @param shardAssignment
    *   static shard-ownership oracle (Slice 3). Used by both paths to enforce that the proof's MG actually belongs to the claimed shard —
    *   defence against a misbehaving shard committee that signs a checkpoint claiming a cross-shard MG's state.
    * @param lookupShardCheckpoint
    *   per-shard checkpoint lookup callback (see [[ShardCheckpointLookup]]). Production wiring resolves this from
    *   `ShardChainStore.bestTip`.
    * @param perMgEntriesFor
    *   per-MG component-entry lookup (see [[PerMgEntriesLookup]]) — the hex-keyed MPT entries the generate path builds the per-MG sub-trie
    *   from (so the proof's witness chain terminates at `perMetagraphMptRoots(mg)`, the PIN-1 component-addressable root). Production
    *   wiring reconstructs the MG state off gl0's finalized `GlobalStateReader` and routes it through
    *   `GlobalStateConverter.currencySnapshotMgEntries`; tests supply the bytes directly.
    *
    * The implicit `Hasher[F]` is required to re-derive the checkpoint's canonical hash on the verify path (mirrors
    * `ShardChainStore.deriveHash`); `Parallel` + `JsonSerializer` are required to build the per-MG sub-trie
    * (`MerklePatriciaTrie.makeParallelFromBytes`).
    */
  def make[F[_]: Async: Parallel: Hasher: JsonSerializer](
    shardAssignment: ShardAssignment[F],
    lookupShardCheckpoint: ShardCheckpointLookup[F],
    perMgEntriesFor: PerMgEntriesLookup[F]
  ): ShardSubtreeProofService[F] = new ShardSubtreeProofService[F] {

    def generateProofForMetagraph(
      shardId: ShardId,
      metagraphAddress: Address,
      key: GlobalStateKey
    ): F[Option[ShardSubtreeProof]] =
      shardAssignment.shardIdFor(metagraphAddress).flatMap { ownerShard =>
        if (ownerShard =!= shardId) {
          // Caller asked the wrong shard for this MG. The static assignment is cluster-wide, so this
          // is a programming error / a probing peer / a stale config — surface as "no proof" so the
          // HTTP layer can map to 400, distinguishing from "no checkpoint" → 404 / 503.
          (None: Option[ShardSubtreeProof]).pure[F]
        } else {
          lookupShardCheckpoint(shardId).flatMap {
            case None =>
              // Shard has no current checkpoint (bootstrap, paused, etc.). Caller resolves to 503.
              (None: Option[ShardSubtreeProof]).pure[F]

            case Some(signedCheckpoint) =>
              val checkpoint = signedCheckpoint.value
              checkpoint.derivedStateDelta.perMetagraphMptRoots.get(metagraphAddress) match {
                case None =>
                  // The MG owns this shard, but the current checkpoint didn't include any state for
                  // it (empty-cycle, or first-write pending). Caller resolves to 404 — the key isn't
                  // proovable at this anchor.
                  (None: Option[ShardSubtreeProof]).pure[F]

                case Some(perMgRoot) =>
                  // PIN-1: build the proof over the per-MG SUB-TRIE (whose `rootHash` is the committed `perMgRoot`), NOT the global trie —
                  // so the witness chain terminates at `perMgRoot` and `verifyProof` can confirm it. The sub-trie is built from the same
                  // `currencySnapshotMgEntries` bytes the committed root commits to (supplied by `perMgEntriesFor`).
                  Hasher[F].hash(checkpoint.signingPreimage).flatMap { cpHash =>
                    perMgEntriesFor(metagraphAddress).flatMap {
                      case None =>
                        // No reconstructible per-MG state at the serve anchor (never-seen MG / pre-genesis). Caller resolves to 404.
                        (None: Option[ShardSubtreeProof]).pure[F]

                      case Some(entries) =>
                        GlobalStateKey.toHex[F](key).flatMap { hexKey =>
                          MerklePatriciaTrie.makeParallelFromBytes[F](entries).flatMap { trie =>
                            // CONSISTENCY GUARD: the rebuilt sub-trie's root MUST equal the committee-attested `perMgRoot`. If the serve
                            // anchor's reconstructed state has drifted from what the checkpoint attested (read-after-write staleness past
                            // the §8.3 one-snapshot bound), the proof would witness against a root the checkpoint never signed and the
                            // consumer's `verifyProof` cross-check would reject it anyway — so refuse to emit rather than ship a proof that
                            // cannot verify. Surfaces as None ⇒ 404 (regenerate once gl0 catches up). Empty-MG entries ⇒ `Hash.empty` root.
                            val rebuiltRoot =
                              if (entries.isEmpty) Hash.empty else trie.rootHash.value
                            if (rebuiltRoot =!= perMgRoot)
                              (None: Option[ShardSubtreeProof]).pure[F]
                            else {
                              val prover = MerklePatriciaSingleInclusionProver.make[F](trie)
                              prover.attestPath(hexKey).map {
                                case Left(_) =>
                                  // PathNotFound / etc. — the key is absent from THIS MG's sub-trie. Surface as None ⇒ 404 (key absent).
                                  // v2 absence-proofs would distinguish empty-trie vs key-not-in-trie.
                                  None: Option[ShardSubtreeProof]
                                case Right(mptProof) =>
                                  // Package the proof with the committed per-MG root. `value` is not populated here — it travels alongside
                                  // the proof on the wire; the HTTP route layer fills it from the MPT lookup.
                                  ShardSubtreeProof(
                                    shardCheckpointHash = cpHash,
                                    metagraphAddress = metagraphAddress,
                                    perMgMptRoot = perMgRoot,
                                    key = key,
                                    value = None,
                                    mptProof = mptProof
                                  ).some
                              }
                            }
                          }
                        }
                    }
                  }
              }
          }
        }
      }

    def verifyProof(
      shardCheckpoint: Signed[ShardCheckpoint],
      proof: ShardSubtreeProof
    ): F[Boolean] = {
      val checkpoint = shardCheckpoint.value

      shardAssignment.shardIdFor(proof.metagraphAddress).flatMap { ownerShard =>
        // Defence-in-depth: the proof's MG must actually be owned by the checkpoint's shard per the
        // static assignment. A misbehaving committee that signs a checkpoint claiming a foreign MG's
        // state is structurally rejected here.
        if (ownerShard =!= checkpoint.shardId) {
          false.pure[F]
        } else {
          val claimedRoot = checkpoint.derivedStateDelta.perMetagraphMptRoots.get(proof.metagraphAddress)

          if (!claimedRoot.contains(proof.perMgMptRoot)) {
            // The proof claims a root that doesn't match what this checkpoint signed. Either the
            // proof is from a different (perhaps stale) checkpoint, or the proof has been tampered
            // with after generation. Reject.
            false.pure[F]
          } else {
            // Re-derive the canonical checkpoint hash and cross-check the proof claims to anchor at
            // this checkpoint. Routes through `Hasher[F]` over the canonical preimage — same byte
            // shape `ShardChainStore.deriveHash` uses.
            Hasher[F].hash(checkpoint.signingPreimage).flatMap { actualHash =>
              if (actualHash =!= proof.shardCheckpointHash) {
                false.pure[F]
              } else {
                // All envelope cross-checks pass — run the standard MPT verifier against the
                // checkpoint's per-MG root.
                val verifier = MerklePatriciaInclusionVerifier.make[F](proof.perMgMptRoot)
                verifier.confirm(proof.mptProof).map(_.isRight)
              }
            }
          }
        }
      }
    }
  }
}
