package io.constellationnetwork.node.shared.domain.nakamoto.sharding

import cats.effect.Async
import cats.syntax.all._

import io.constellationnetwork.node.shared.domain.nakamoto.overlay.BranchId
import io.constellationnetwork.node.shared.domain.nakamoto.{HistoricalMptProofService, ShardAssignment}
import io.constellationnetwork.schema.SnapshotOrdinal
import io.constellationnetwork.schema.address.Address
import io.constellationnetwork.schema.mpt.GlobalStateKey
import io.constellationnetwork.schema.sharding.{ShardCheckpoint, ShardId}
import io.constellationnetwork.security.Hasher
import io.constellationnetwork.security.hash.Hash
import io.constellationnetwork.security.hex.Hex
import io.constellationnetwork.security.mpt.prover.attestation.MerklePatriciaInclusionProof
import io.constellationnetwork.security.mpt.verifier.MerklePatriciaInclusionVerifier
import io.constellationnetwork.security.signature.Signed

import derevo.circe.magnolia.{decoder, encoder}
import derevo.derive

/** Cross-shard MPT inclusion proof envelope — Slice 10 of `docs/nakamoto/HIERARCHICAL-SHARD-CHECKPOINTS-DESIGN.md` §8.5/§8.6.
  *
  * The on-wire shape carried between shard committees when shard X needs to verify a key against shard Y's MPT state (e.g.
  * `SpendActionValidator` referencing an `AllowSpend` whose source belongs to a metagraph assigned to a different shard). The envelope
  * packs:
  *
  *   - `shardCheckpointHash` — the canonical [[ShardCheckpoint]] hash this proof is anchored at. The consumer looks up this hash in gl0's
  *     last-finalized snapshot's `shardCheckpoints[shardId]` to find the trusted root (per §8.6 step 1).
  *   - `metagraphAddress` — the per-MG subtree the proof witnesses. The consumer cross-checks this matches the requested MG.
  *   - `perMgMptRoot` — the verifier root: lifted from the checkpoint's `derivedStateDelta.perMetagraphMptRoots[metagraphAddress]`. The
  *     consumer runs the standard `MerklePatriciaInclusionVerifier` against this hash (per §8.6 step 2).
  *   - `key` — the [[GlobalStateKey]] this proof addresses (carried as a structured value so the consumer can re-derive the canonical hex
  *     path independently — same key encoding used by [[HistoricalMptProofService]]).
  *   - `value` — `Some(hex)` carrying hex-encoded value bytes for membership proofs (v1 supported), `None` reserved for future
  *     proof-of-absence (v2 — the underlying [[MerklePatriciaInclusionVerifier]] currently has no absence-witness support, so v1 only ships
  *     membership proofs and surfaces absence by [[ShardSubtreeProofService.generateProofForMetagraph]] returning `None`). The wire
  *     encoding uses [[Hex]] rather than raw `Array[Byte]` so the envelope has stable Circe + Eq instances — the verifier doesn't care
  *     about the value bytes (only the proof's leaf commitment matters structurally); this field is for the consumer to read the value once
  *     verification passes.
  *   - `mptProof` — the standard MPT inclusion proof (path + witness commitments) generated by [[HistoricalMptProofService]].
  *
  * '''Greenfield rule''' (per `[[feedback-greenfield-no-wire-compat]]`): fresh envelope for the cross-shard read path. No compat ceremony.
  *
  * '''Wire-byte stability.''' Field order and field set here is part of the cross-shard protocol contract. Adding a field, reordering, or
  * wrapping in `Option` silently changes the derevo magnolia-derived Circe JSON. Bump the case class explicitly (`ShardSubtreeProofV2`) and
  * version the verifier branch — same frozen-shape discipline as [[io.constellationnetwork.schema.sharding.ShardCheckpoint]].
  */
@derive(encoder, decoder)
final case class ShardSubtreeProof(
  shardCheckpointHash: Hash,
  metagraphAddress: Address,
  perMgMptRoot: Hash,
  key: GlobalStateKey,
  value: Option[Hex],
  mptProof: MerklePatriciaInclusionProof
)

/** Cross-shard MPT inclusion proof service — Slice 10 of `docs/nakamoto/HIERARCHICAL-SHARD-CHECKPOINTS-DESIGN.md` §8.5.
  *
  * '''Scope''' (per slice 10 task spec):
  *   - Generate inclusion proofs scoped to a single shard's subtree (`generateProofForMetagraph`).
  *   - Verify proofs against a committee-signed shard checkpoint's per-MG MPT root (`verifyProof`).
  *
  * '''Reuse''' — both paths route through existing primitives:
  *   - Generation: [[HistoricalMptProofService]] (`proofAtBranch`) — the per-shard subtree proof IS structurally identical to a standard
  *     MPT inclusion proof; the only difference is the root the consumer verifies against (per design doc §8.5 — "structurally identical
  *     (same MPT verifier on the consumer side); the difference is the root").
  *   - Verification: [[MerklePatriciaInclusionVerifier]] — standard MPT verifier rooted at the per-MG subtree root from the shard
  *     checkpoint.
  *
  * '''What this slice does NOT do''':
  *   - Maintain per-shard subtree producers — v1 reuses the global MPT and treats the per-MG subtree root in the checkpoint as the
  *     verification anchor. v2 may introduce per-shard producers if the global-MPT-as-substrate ceases to scale.
  *   - Proof-of-absence — the underlying `MerklePatriciaInclusionVerifier` has no absence-witness support; generate returns `None` for
  *     absent keys instead of fabricating an absence proof. v2 target.
  *   - Handle the cross-shard read protocol itself (§8.6 P2P request shape) — that's slice 11/14 wiring. This slice provides the
  *     prover/verifier primitives the wire path will call.
  *
  * '''Read-after-write staleness''' (per design doc §8.3): cross-shard reads see state up to one gl0 snapshot stale (~7s). The service
  * surfaces this naturally — proofs reference a specific checkpoint hash; the proof is consistent with that checkpoint's state. No special
  * handling in v1.
  *
  * '''Greenfield rule''' (per `[[feedback-greenfield-no-wire-compat]]`): fresh prover/verifier for the cross-shard read path. No compat
  * ceremony.
  *
  * '''HOCON rule''' (per `[[feedback-prefer-hocon-over-sysenv]]`): all knobs are constructor parameters; production wiring passes typed
  * `SharedConfig.nakamoto.sharding.*` values via the injected [[ShardAssignment]]. No `sys.env.get` anywhere.
  */
trait ShardSubtreeProofService[F[_]] {

  /** Generate an inclusion proof for `key` under `metagraphAddress`'s subtree, attributable to the shard `shardId`. Caller pre-computes
    * `shardId` (typically via [[ShardAssignment.shardIdFor]]); the service cross-checks that `shardId` does in fact own `metagraphAddress`
    * per the deterministic static assignment and returns `None` on mismatch.
    *
    * Returns:
    *   - `Some(proof)` when (a) the shard owns the MG per static assignment, (b) a current checkpoint exists for the shard (resolved via
    *     the constructor-supplied `lookupShardCheckpoint`), AND (c) the key resolves to a value in the underlying MPT (membership case).
    *   - `None` when ANY of (a), (b), (c) doesn't hold. The caller distinguishes "shard not active" from "key absent" via the absence of a
    *     checkpoint at the lookup callback (returned to the caller as part of the wire-level 404 vs 503 mapping in the HTTP route — see
    *     `ShardProofRoutes` for that mapping).
    */
  def generateProofForMetagraph(
    shardId: ShardId,
    metagraphAddress: Address,
    key: GlobalStateKey
  ): F[Option[ShardSubtreeProof]]

  /** Verify a proof against its claimed shard checkpoint's per-MG MPT root.
    *
    * Returns `true` iff ALL of the following hold:
    *   - The proof's `perMgMptRoot` matches the checkpoint's `derivedStateDelta.perMetagraphMptRoots[metagraphAddress]`.
    *   - The proof's `shardCheckpointHash` matches the supplied `shardCheckpoint`'s canonical hash (re-derived via `Hasher[F]` over
    *     `signingPreimage`).
    *   - The proof's `metagraphAddress` is owned by `shardCheckpoint.shardId` per the static assignment.
    *   - The standard `MerklePatriciaInclusionVerifier` accepts the proof against `perMgMptRoot`.
    *
    * Tampered value bytes are caught structurally: the proof's leaf commitment embeds `dataDigest = Hasher.hash(value)`, and the leaf's
    * outer digest is part of the witness chain. Changing the value without re-deriving `dataDigest` invalidates the leaf commitment, which
    * the verifier rejects. Changing the value AND `dataDigest` invalidates the witness chain upward.
    *
    * The verify path also requires the proof's `value` (the bytes the proof's leaf commits to) to match what the proof anchors at. The
    * caller supplies the value to verify alongside the proof — the service does NOT trust the `value` field embedded in the proof envelope
    * for the verify path (defence-in-depth: the receiver should compute / receive `value` independently and pass it here, matching the
    * typical pattern where the wire response is `{ value, proof }` and the consumer validates the proof commits to that value).
    */
  def verifyProof(
    shardCheckpoint: Signed[ShardCheckpoint],
    proof: ShardSubtreeProof
  ): F[Boolean]
}

object ShardSubtreeProofService {

  /** Lookup callback for the most recent committee-signed shard checkpoint for a given shard. The production wiring resolves this from the
    * per-shard `ShardChainStore` (Slice 5) — typically `chainStore.bestTip.map(_.signed)`. Decoupling via callback so this slice doesn't
    * pull `ShardChainStore` as a transitive dependency — that's slice 11/14 wiring.
    *
    * Returns `None` when the shard has no current checkpoint (bootstrap, paused shard, etc.) — the service maps that to "cannot generate
    * proof" and surfaces it to the HTTP layer as 404 / 503 per the route's response-code policy.
    */
  type ShardCheckpointLookup[F[_]] = ShardId => F[Option[Signed[ShardCheckpoint]]]

  /** Construct a [[ShardSubtreeProofService]].
    *
    * @param mptProofService
    *   the underlying MPT proof primitive — produces standard [[MerklePatriciaInclusionProof]]s scoped to a [[BranchId]] +
    *   [[SnapshotOrdinal]] view of the global MPT. Slice 10 uses this directly; v2 (per-shard producers) would swap the underlying trie
    *   source while keeping this trait's surface stable.
    * @param shardAssignment
    *   static shard-ownership oracle (Slice 3). Used by both paths to enforce that the proof's MG actually belongs to the claimed shard —
    *   defence against a misbehaving shard committee that signs a checkpoint claiming a cross-shard MG's state.
    * @param lookupShardCheckpoint
    *   per-shard checkpoint lookup callback (see [[ShardCheckpointLookup]]). Production wiring resolves this from
    *   `ShardChainStore.bestTip`.
    * @param branchForGeneration
    *   the [[BranchId]] the generate path materializes the MPT at. Typically the current canonical branch (e.g.
    *   `chainStore.bestTip.map(BranchId(_))` for gl0 — but the cross-shard read protocol in §8.6 anchors at gl0's last-finalized snapshot,
    *   so production wiring would pass a finalized-branch id here. Tests pass `BranchId.base` for a base-trie view.
    * @param ordinalForGeneration
    *   the [[SnapshotOrdinal]] the generate path materializes the MPT at — paired with `branchForGeneration`. Production wiring passes
    *   `snapshotStorage.head.map(_.ordinal)`; tests pass a fixed ordinal.
    *
    * The implicit `Hasher[F]` is required to re-derive the checkpoint's canonical hash on the verify path (mirrors
    * `ShardChainStore.deriveHash`).
    */
  def make[F[_]: Async: Hasher](
    mptProofService: HistoricalMptProofService[F],
    shardAssignment: ShardAssignment[F],
    lookupShardCheckpoint: ShardCheckpointLookup[F],
    branchForGeneration: BranchId,
    ordinalForGeneration: SnapshotOrdinal
  ): ShardSubtreeProofService[F] = new ShardSubtreeProofService[F] {

    def generateProofForMetagraph(
      shardId: ShardId,
      metagraphAddress: Address,
      key: GlobalStateKey
    ): F[Option[ShardSubtreeProof]] =
      shardAssignment.shardIdFor(metagraphAddress).flatMap { ownerShard =>
        if (ownerShard =!= shardId) {
          // Caller asked the wrong shard for this MG. The static assignment is cluster-wide, so this
          // is a programming error / a probing peer / a stale config — surface as "no proof" so the
          // HTTP layer can map to 400, distinguishing from "no checkpoint" → 404 / 503.
          (None: Option[ShardSubtreeProof]).pure[F]
        } else {
          lookupShardCheckpoint(shardId).flatMap {
            case None =>
              // Shard has no current checkpoint (bootstrap, paused, etc.). Caller resolves to 503.
              (None: Option[ShardSubtreeProof]).pure[F]

            case Some(signedCheckpoint) =>
              val checkpoint = signedCheckpoint.value
              checkpoint.derivedStateDelta.perMetagraphMptRoots.get(metagraphAddress) match {
                case None =>
                  // The MG owns this shard, but the current checkpoint didn't include any state for
                  // it (empty-cycle, or first-write pending). Caller resolves to 404 — the key isn't
                  // proovable at this anchor.
                  (None: Option[ShardSubtreeProof]).pure[F]

                case Some(perMgRoot) =>
                  for {
                    cpHash <- Hasher[F].hash(checkpoint.signingPreimage)
                    proofE <- mptProofService.proofAtBranch(branchForGeneration, ordinalForGeneration, key)
                    out <- proofE match {
                      case Left(_) =>
                        // PathNotFound / TrieBuildFailed / etc. — surface as None so the caller maps
                        // to 404 (key absent). v2 absence-proofs would distinguish the empty-trie
                        // vs key-not-in-trie cases.
                        (None: Option[ShardSubtreeProof]).pure[F]

                      case Right(mptProof) =>
                        // Slice 10 v1: package the proof with the per-MG root from the checkpoint.
                        // The `value` field is not populated here — it travels alongside the proof
                        // on the wire (per §8.6 JSON shape `{ "value": ..., "proof": ..., "rootedAtCheckpoint": ... }`).
                        // The HTTP route layer fills `value` from the underlying MPT lookup.
                        ShardSubtreeProof(
                          shardCheckpointHash = cpHash,
                          metagraphAddress = metagraphAddress,
                          perMgMptRoot = perMgRoot,
                          key = key,
                          value = None,
                          mptProof = mptProof
                        ).some.pure[F]
                    }
                  } yield out
              }
          }
        }
      }

    def verifyProof(
      shardCheckpoint: Signed[ShardCheckpoint],
      proof: ShardSubtreeProof
    ): F[Boolean] = {
      val checkpoint = shardCheckpoint.value

      shardAssignment.shardIdFor(proof.metagraphAddress).flatMap { ownerShard =>
        // Defence-in-depth: the proof's MG must actually be owned by the checkpoint's shard per the
        // static assignment. A misbehaving committee that signs a checkpoint claiming a foreign MG's
        // state is structurally rejected here.
        if (ownerShard =!= checkpoint.shardId) {
          false.pure[F]
        } else {
          val claimedRoot = checkpoint.derivedStateDelta.perMetagraphMptRoots.get(proof.metagraphAddress)

          if (!claimedRoot.contains(proof.perMgMptRoot)) {
            // The proof claims a root that doesn't match what this checkpoint signed. Either the
            // proof is from a different (perhaps stale) checkpoint, or the proof has been tampered
            // with after generation. Reject.
            false.pure[F]
          } else {
            // Re-derive the canonical checkpoint hash and cross-check the proof claims to anchor at
            // this checkpoint. Routes through `Hasher[F]` over the canonical preimage — same byte
            // shape `ShardChainStore.deriveHash` uses.
            Hasher[F].hash(checkpoint.signingPreimage).flatMap { actualHash =>
              if (actualHash =!= proof.shardCheckpointHash) {
                false.pure[F]
              } else {
                // All envelope cross-checks pass — run the standard MPT verifier against the
                // checkpoint's per-MG root.
                val verifier = MerklePatriciaInclusionVerifier.make[F](proof.perMgMptRoot)
                verifier.confirm(proof.mptProof).map(_.isRight)
              }
            }
          }
        }
      }
    }
  }
}
