// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/sidecar.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A snapshot produced by a slot winner, broadcast via GossipSub.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                       // 32 bytes, snapshot hash
	Slot          int64                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`                                      // slot number
	Ordinal       int64                  `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`                                // snapshot ordinal
	ParentHash    []byte                 `protobuf:"bytes,4,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`         // 32 bytes, parent snapshot hash
	VrfProof      []byte                 `protobuf:"bytes,5,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`               // 80 bytes, VRF proof (Gamma || c || s)
	VrfPublicKey  []byte                 `protobuf:"bytes,6,opt,name=vrf_public_key,json=vrfPublicKey,proto3" json:"vrf_public_key,omitempty"` // 32 bytes, Ed25519 VRF public key
	Eta           []byte                 `protobuf:"bytes,7,opt,name=eta,proto3" json:"eta,omitempty"`                                         // 32 bytes, epoch randomness
	Payload       []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`                                 // serialized snapshot body (opaque to sidecar)
	ProducerId    []byte                 `protobuf:"bytes,9,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`         // peer identity of the producer
	ParentSlot    int64                  `protobuf:"varint,10,opt,name=parent_slot,json=parentSlot,proto3" json:"parent_slot,omitempty"`       // slot of parent snapshot (for slot gap verification)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Snapshot) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Snapshot) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *Snapshot) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Snapshot) GetVrfProof() []byte {
	if x != nil {
		return x.VrfProof
	}
	return nil
}

func (x *Snapshot) GetVrfPublicKey() []byte {
	if x != nil {
		return x.VrfPublicKey
	}
	return nil
}

func (x *Snapshot) GetEta() []byte {
	if x != nil {
		return x.Eta
	}
	return nil
}

func (x *Snapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Snapshot) GetProducerId() []byte {
	if x != nil {
		return x.ProducerId
	}
	return nil
}

func (x *Snapshot) GetParentSlot() int64 {
	if x != nil {
		return x.ParentSlot
	}
	return 0
}

// A validator's endorsement of a chain tip.
type TipAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TipHash       []byte                 `protobuf:"bytes,1,opt,name=tip_hash,json=tipHash,proto3" json:"tip_hash,omitempty"`           // 32 bytes, hash of endorsed snapshot
	TipSlot       int64                  `protobuf:"varint,2,opt,name=tip_slot,json=tipSlot,proto3" json:"tip_slot,omitempty"`          // slot of that snapshot
	TipOrdinal    int64                  `protobuf:"varint,3,opt,name=tip_ordinal,json=tipOrdinal,proto3" json:"tip_ordinal,omitempty"` // ordinal of that snapshot
	AttestedAt    int64                  `protobuf:"varint,4,opt,name=attested_at,json=attestedAt,proto3" json:"attested_at,omitempty"` // slot when attestation was created
	AttesterId    []byte                 `protobuf:"bytes,5,opt,name=attester_id,json=attesterId,proto3" json:"attester_id,omitempty"`  // peer identity of the attester
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                      // signature over (tip_hash || tip_slot)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TipAttestation) Reset() {
	*x = TipAttestation{}
	mi := &file_proto_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TipAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipAttestation) ProtoMessage() {}

func (x *TipAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipAttestation.ProtoReflect.Descriptor instead.
func (*TipAttestation) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *TipAttestation) GetTipHash() []byte {
	if x != nil {
		return x.TipHash
	}
	return nil
}

func (x *TipAttestation) GetTipSlot() int64 {
	if x != nil {
		return x.TipSlot
	}
	return 0
}

func (x *TipAttestation) GetTipOrdinal() int64 {
	if x != nil {
		return x.TipOrdinal
	}
	return 0
}

func (x *TipAttestation) GetAttestedAt() int64 {
	if x != nil {
		return x.AttestedAt
	}
	return 0
}

func (x *TipAttestation) GetAttesterId() []byte {
	if x != nil {
		return x.AttesterId
	}
	return nil
}

func (x *TipAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// A generic signed rumor — used to carry events, BFT consensus messages,
// and other Tessellation gossip payloads on top of GossipSub. The sidecar
// treats the body as opaque bytes; the JVM is responsible for serialization,
// signing, and validation.
type Rumor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed rumor envelope, JSON-serialized by the JVM and wrapped in the
	// standard Tessellation `Signed[RumorRaw]` shape. Opaque to the sidecar.
	SignedRumorBytes []byte `protobuf:"bytes,1,opt,name=signed_rumor_bytes,json=signedRumorBytes,proto3" json:"signed_rumor_bytes,omitempty"`
	// Content type discriminator (e.g. "io.constellationnetwork...Event").
	// Carried alongside the bytes for cheap routing/metrics on the sidecar.
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Origin peer id (for logging/dedup hints — authoritative origin is in the
	// signed envelope).
	OriginId      []byte `protobuf:"bytes,3,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rumor) Reset() {
	*x = Rumor{}
	mi := &file_proto_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rumor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rumor) ProtoMessage() {}

func (x *Rumor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rumor.ProtoReflect.Descriptor instead.
func (*Rumor) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *Rumor) GetSignedRumorBytes() []byte {
	if x != nil {
		return x.SignedRumorBytes
	}
	return nil
}

func (x *Rumor) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Rumor) GetOriginId() []byte {
	if x != nil {
		return x.OriginId
	}
	return nil
}

// A state channel snapshot binary produced by a metagraph CL0, broadcast
// to all GL0 nodes via GossipSub. Replaces the HTTP POST path that suffered
// from retry-cap starvation under transient rejections. The sidecar treats
// the binary bytes as opaque; the JVM serializes Signed[StateChannelSnapshotBinary]
// the same way the HTTP path does (JsonBrotliBinarySerializer).
type MetagraphBinary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metagraph address (DAG base58 string).
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Signed[StateChannelSnapshotBinary] bytes, opaque to the sidecar.
	Binary        []byte `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetagraphBinary) Reset() {
	*x = MetagraphBinary{}
	mi := &file_proto_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetagraphBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetagraphBinary) ProtoMessage() {}

func (x *MetagraphBinary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetagraphBinary.ProtoReflect.Descriptor instead.
func (*MetagraphBinary) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *MetagraphBinary) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MetagraphBinary) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

// Envelope for GossipSub messages.
type GossipMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*GossipMessage_Snapshot
	//	*GossipMessage_Attestation
	//	*GossipMessage_Rumor
	//	*GossipMessage_MetagraphBinary
	Body          isGossipMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_proto_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *GossipMessage) GetBody() isGossipMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GossipMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Body.(*GossipMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *GossipMessage) GetAttestation() *TipAttestation {
	if x != nil {
		if x, ok := x.Body.(*GossipMessage_Attestation); ok {
			return x.Attestation
		}
	}
	return nil
}

func (x *GossipMessage) GetRumor() *Rumor {
	if x != nil {
		if x, ok := x.Body.(*GossipMessage_Rumor); ok {
			return x.Rumor
		}
	}
	return nil
}

func (x *GossipMessage) GetMetagraphBinary() *MetagraphBinary {
	if x != nil {
		if x, ok := x.Body.(*GossipMessage_MetagraphBinary); ok {
			return x.MetagraphBinary
		}
	}
	return nil
}

type isGossipMessage_Body interface {
	isGossipMessage_Body()
}

type GossipMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type GossipMessage_Attestation struct {
	Attestation *TipAttestation `protobuf:"bytes,2,opt,name=attestation,proto3,oneof"`
}

type GossipMessage_Rumor struct {
	Rumor *Rumor `protobuf:"bytes,3,opt,name=rumor,proto3,oneof"`
}

type GossipMessage_MetagraphBinary struct {
	MetagraphBinary *MetagraphBinary `protobuf:"bytes,4,opt,name=metagraph_binary,json=metagraphBinary,proto3,oneof"`
}

func (*GossipMessage_Snapshot) isGossipMessage_Body() {}

func (*GossipMessage_Attestation) isGossipMessage_Body() {}

func (*GossipMessage_Rumor) isGossipMessage_Body() {}

func (*GossipMessage_MetagraphBinary) isGossipMessage_Body() {}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *PublishResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which message types to receive. Empty = all.
	Topics        []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type PeerCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCountRequest) Reset() {
	*x = PeerCountRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCountRequest) ProtoMessage() {}

func (x *PeerCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCountRequest.ProtoReflect.Descriptor instead.
func (*PeerCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{7}
}

type PeerCountResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Total                 int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	MeshSnapshots         int32                  `protobuf:"varint,2,opt,name=mesh_snapshots,json=meshSnapshots,proto3" json:"mesh_snapshots,omitempty"`                           // peers in snapshot topic mesh
	MeshAttestations      int32                  `protobuf:"varint,3,opt,name=mesh_attestations,json=meshAttestations,proto3" json:"mesh_attestations,omitempty"`                  // peers in attestation topic mesh
	MeshRumors            int32                  `protobuf:"varint,4,opt,name=mesh_rumors,json=meshRumors,proto3" json:"mesh_rumors,omitempty"`                                    // peers in rumor topic mesh
	MeshMetagraphBinaries int32                  `protobuf:"varint,5,opt,name=mesh_metagraph_binaries,json=meshMetagraphBinaries,proto3" json:"mesh_metagraph_binaries,omitempty"` // peers in metagraph binary topic mesh
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PeerCountResponse) Reset() {
	*x = PeerCountResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCountResponse) ProtoMessage() {}

func (x *PeerCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCountResponse.ProtoReflect.Descriptor instead.
func (*PeerCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *PeerCountResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PeerCountResponse) GetMeshSnapshots() int32 {
	if x != nil {
		return x.MeshSnapshots
	}
	return 0
}

func (x *PeerCountResponse) GetMeshAttestations() int32 {
	if x != nil {
		return x.MeshAttestations
	}
	return 0
}

func (x *PeerCountResponse) GetMeshRumors() int32 {
	if x != nil {
		return x.MeshRumors
	}
	return 0
}

func (x *PeerCountResponse) GetMeshMetagraphBinaries() int32 {
	if x != nil {
		return x.MeshMetagraphBinaries
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	PeerCount     int32                  `protobuf:"varint,3,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

// A point on a chain, used for intersection finding.
type ChainPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Ordinal       int64                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainPoint) Reset() {
	*x = ChainPoint{}
	mi := &file_proto_sidecar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainPoint) ProtoMessage() {}

func (x *ChainPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainPoint.ProtoReflect.Descriptor instead.
func (*ChainPoint) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{11}
}

func (x *ChainPoint) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ChainPoint) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

// Request specific snapshots by hash (up to 64 per request).
type FetchSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSnapshotsRequest) Reset() {
	*x = FetchSnapshotsRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSnapshotsRequest) ProtoMessage() {}

func (x *FetchSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*FetchSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{12}
}

func (x *FetchSnapshotsRequest) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

// Find the most recent common ancestor between two chains.
// Client sends sparse chain points (e.g. tip, tip-1, tip-2, tip-4, tip-8, ...genesis).
type FindIntersectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*ChainPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindIntersectionRequest) Reset() {
	*x = FindIntersectionRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindIntersectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindIntersectionRequest) ProtoMessage() {}

func (x *FindIntersectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindIntersectionRequest.ProtoReflect.Descriptor instead.
func (*FindIntersectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{13}
}

func (x *FindIntersectionRequest) GetPoints() []*ChainPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type FindIntersectionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Found               bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	IntersectionHash    []byte                 `protobuf:"bytes,2,opt,name=intersection_hash,json=intersectionHash,proto3" json:"intersection_hash,omitempty"`
	IntersectionOrdinal int64                  `protobuf:"varint,3,opt,name=intersection_ordinal,json=intersectionOrdinal,proto3" json:"intersection_ordinal,omitempty"`
	TipHash             []byte                 `protobuf:"bytes,4,opt,name=tip_hash,json=tipHash,proto3" json:"tip_hash,omitempty"` // responder's current best tip
	TipOrdinal          int64                  `protobuf:"varint,5,opt,name=tip_ordinal,json=tipOrdinal,proto3" json:"tip_ordinal,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindIntersectionResponse) Reset() {
	*x = FindIntersectionResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindIntersectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindIntersectionResponse) ProtoMessage() {}

func (x *FindIntersectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindIntersectionResponse.ProtoReflect.Descriptor instead.
func (*FindIntersectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{14}
}

func (x *FindIntersectionResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindIntersectionResponse) GetIntersectionHash() []byte {
	if x != nil {
		return x.IntersectionHash
	}
	return nil
}

func (x *FindIntersectionResponse) GetIntersectionOrdinal() int64 {
	if x != nil {
		return x.IntersectionOrdinal
	}
	return 0
}

func (x *FindIntersectionResponse) GetTipHash() []byte {
	if x != nil {
		return x.TipHash
	}
	return nil
}

func (x *FindIntersectionResponse) GetTipOrdinal() int64 {
	if x != nil {
		return x.TipOrdinal
	}
	return 0
}

type GetPeerTipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerTipRequest) Reset() {
	*x = GetPeerTipRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerTipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerTipRequest) ProtoMessage() {}

func (x *GetPeerTipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerTipRequest.ProtoReflect.Descriptor instead.
func (*GetPeerTipRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{15}
}

type PeerTipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Ordinal       int64                  `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Slot          int64                  `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerTipResponse) Reset() {
	*x = PeerTipResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerTipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerTipResponse) ProtoMessage() {}

func (x *PeerTipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerTipResponse.ProtoReflect.Descriptor instead.
func (*PeerTipResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{16}
}

func (x *PeerTipResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *PeerTipResponse) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *PeerTipResponse) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type ServeSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeSnapshotsRequest) Reset() {
	*x = ServeSnapshotsRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeSnapshotsRequest) ProtoMessage() {}

func (x *ServeSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ServeSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{17}
}

func (x *ServeSnapshotsRequest) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type ServeChainPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeChainPointsRequest) Reset() {
	*x = ServeChainPointsRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeChainPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeChainPointsRequest) ProtoMessage() {}

func (x *ServeChainPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeChainPointsRequest.ProtoReflect.Descriptor instead.
func (*ServeChainPointsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{18}
}

type ServeChainPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*ChainPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	TipHash       []byte                 `protobuf:"bytes,2,opt,name=tip_hash,json=tipHash,proto3" json:"tip_hash,omitempty"`
	TipOrdinal    int64                  `protobuf:"varint,3,opt,name=tip_ordinal,json=tipOrdinal,proto3" json:"tip_ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeChainPointsResponse) Reset() {
	*x = ServeChainPointsResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeChainPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeChainPointsResponse) ProtoMessage() {}

func (x *ServeChainPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeChainPointsResponse.ProtoReflect.Descriptor instead.
func (*ServeChainPointsResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{19}
}

func (x *ServeChainPointsResponse) GetPoints() []*ChainPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *ServeChainPointsResponse) GetTipHash() []byte {
	if x != nil {
		return x.TipHash
	}
	return nil
}

func (x *ServeChainPointsResponse) GetTipOrdinal() int64 {
	if x != nil {
		return x.TipOrdinal
	}
	return 0
}

// ─── Backfill: Range-Based Chain Sync ───────────────────────────────
// Lightweight snapshot for backfill — no GlobalSnapshotInfo context.
// Cuts per-snapshot transfer from 100KB-10MB to 1-5KB.
type BackfillSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Slot          int64                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Ordinal       int64                  `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	ParentHash    []byte                 `protobuf:"bytes,4,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	VrfProof      []byte                 `protobuf:"bytes,5,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`
	VrfPublicKey  []byte                 `protobuf:"bytes,6,opt,name=vrf_public_key,json=vrfPublicKey,proto3" json:"vrf_public_key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"` // Signed[GlobalIncrementalSnapshot] JSON only, NO context
	ProducerId    []byte                 `protobuf:"bytes,8,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	ParentSlot    int64                  `protobuf:"varint,9,opt,name=parent_slot,json=parentSlot,proto3" json:"parent_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillSnapshot) Reset() {
	*x = BackfillSnapshot{}
	mi := &file_proto_sidecar_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillSnapshot) ProtoMessage() {}

func (x *BackfillSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillSnapshot.ProtoReflect.Descriptor instead.
func (*BackfillSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{20}
}

func (x *BackfillSnapshot) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BackfillSnapshot) GetSlot() int64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BackfillSnapshot) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *BackfillSnapshot) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BackfillSnapshot) GetVrfProof() []byte {
	if x != nil {
		return x.VrfProof
	}
	return nil
}

func (x *BackfillSnapshot) GetVrfPublicKey() []byte {
	if x != nil {
		return x.VrfPublicKey
	}
	return nil
}

func (x *BackfillSnapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BackfillSnapshot) GetProducerId() []byte {
	if x != nil {
		return x.ProducerId
	}
	return nil
}

func (x *BackfillSnapshot) GetParentSlot() int64 {
	if x != nil {
		return x.ParentSlot
	}
	return 0
}

// Fetch a contiguous range of snapshots by ordinal.
type FetchByRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartOrdinal  int64                  `protobuf:"varint,1,opt,name=start_ordinal,json=startOrdinal,proto3" json:"start_ordinal,omitempty"`  // inclusive
	EndOrdinal    int64                  `protobuf:"varint,2,opt,name=end_ordinal,json=endOrdinal,proto3" json:"end_ordinal,omitempty"`        // inclusive
	TargetPeerId  []byte                 `protobuf:"bytes,3,opt,name=target_peer_id,json=targetPeerId,proto3" json:"target_peer_id,omitempty"` // optional: direct to specific peer for parallel chunking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchByRangeRequest) Reset() {
	*x = FetchByRangeRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchByRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchByRangeRequest) ProtoMessage() {}

func (x *FetchByRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchByRangeRequest.ProtoReflect.Descriptor instead.
func (*FetchByRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{21}
}

func (x *FetchByRangeRequest) GetStartOrdinal() int64 {
	if x != nil {
		return x.StartOrdinal
	}
	return 0
}

func (x *FetchByRangeRequest) GetEndOrdinal() int64 {
	if x != nil {
		return x.EndOrdinal
	}
	return 0
}

func (x *FetchByRangeRequest) GetTargetPeerId() []byte {
	if x != nil {
		return x.TargetPeerId
	}
	return nil
}

// List connected peers (for parallel chunk assignment).
type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_proto_sidecar_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{22}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerIds       [][]byte               `protobuf:"bytes,1,rep,name=peer_ids,json=peerIds,proto3" json:"peer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_proto_sidecar_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidecar_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidecar_proto_rawDescGZIP(), []int{23}
}

func (x *ListPeersResponse) GetPeerIds() [][]byte {
	if x != nil {
		return x.PeerIds
	}
	return nil
}

var File_proto_sidecar_proto protoreflect.FileDescriptor

const file_proto_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sidecar.proto\x12\fnakamoto.p2p\"\x9e\x02\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x03R\x04slot\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x03R\aordinal\x12\x1f\n" +
	"\vparent_hash\x18\x04 \x01(\fR\n" +
	"parentHash\x12\x1b\n" +
	"\tvrf_proof\x18\x05 \x01(\fR\bvrfProof\x12$\n" +
	"\x0evrf_public_key\x18\x06 \x01(\fR\fvrfPublicKey\x12\x10\n" +
	"\x03eta\x18\a \x01(\fR\x03eta\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1f\n" +
	"\vproducer_id\x18\t \x01(\fR\n" +
	"producerId\x12\x1f\n" +
	"\vparent_slot\x18\n" +
	" \x01(\x03R\n" +
	"parentSlot\"\xc7\x01\n" +
	"\x0eTipAttestation\x12\x19\n" +
	"\btip_hash\x18\x01 \x01(\fR\atipHash\x12\x19\n" +
	"\btip_slot\x18\x02 \x01(\x03R\atipSlot\x12\x1f\n" +
	"\vtip_ordinal\x18\x03 \x01(\x03R\n" +
	"tipOrdinal\x12\x1f\n" +
	"\vattested_at\x18\x04 \x01(\x03R\n" +
	"attestedAt\x12\x1f\n" +
	"\vattester_id\x18\x05 \x01(\fR\n" +
	"attesterId\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"u\n" +
	"\x05Rumor\x12,\n" +
	"\x12signed_rumor_bytes\x18\x01 \x01(\fR\x10signedRumorBytes\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\torigin_id\x18\x03 \x01(\fR\boriginId\"C\n" +
	"\x0fMetagraphBinary\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06binary\x18\x02 \x01(\fR\x06binary\"\x88\x02\n" +
	"\rGossipMessage\x124\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x16.nakamoto.p2p.SnapshotH\x00R\bsnapshot\x12@\n" +
	"\vattestation\x18\x02 \x01(\v2\x1c.nakamoto.p2p.TipAttestationH\x00R\vattestation\x12+\n" +
	"\x05rumor\x18\x03 \x01(\v2\x13.nakamoto.p2p.RumorH\x00R\x05rumor\x12J\n" +
	"\x10metagraph_binary\x18\x04 \x01(\v2\x1d.nakamoto.p2p.MetagraphBinaryH\x00R\x0fmetagraphBinaryB\x06\n" +
	"\x04body\"7\n" +
	"\x0fPublishResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"\x12\n" +
	"\x10PeerCountRequest\"\xd6\x01\n" +
	"\x11PeerCountResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12%\n" +
	"\x0emesh_snapshots\x18\x02 \x01(\x05R\rmeshSnapshots\x12+\n" +
	"\x11mesh_attestations\x18\x03 \x01(\x05R\x10meshAttestations\x12\x1f\n" +
	"\vmesh_rumors\x18\x04 \x01(\x05R\n" +
	"meshRumors\x126\n" +
	"\x17mesh_metagraph_binaries\x18\x05 \x01(\x05R\x15meshMetagraphBinaries\"\x0f\n" +
	"\rHealthRequest\"p\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x03 \x01(\x05R\tpeerCount\":\n" +
	"\n" +
	"ChainPoint\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x03R\aordinal\"/\n" +
	"\x15FetchSnapshotsRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes\"K\n" +
	"\x17FindIntersectionRequest\x120\n" +
	"\x06points\x18\x01 \x03(\v2\x18.nakamoto.p2p.ChainPointR\x06points\"\xcc\x01\n" +
	"\x18FindIntersectionResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12+\n" +
	"\x11intersection_hash\x18\x02 \x01(\fR\x10intersectionHash\x121\n" +
	"\x14intersection_ordinal\x18\x03 \x01(\x03R\x13intersectionOrdinal\x12\x19\n" +
	"\btip_hash\x18\x04 \x01(\fR\atipHash\x12\x1f\n" +
	"\vtip_ordinal\x18\x05 \x01(\x03R\n" +
	"tipOrdinal\"\x13\n" +
	"\x11GetPeerTipRequest\"S\n" +
	"\x0fPeerTipResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\x03R\aordinal\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\x03R\x04slot\"/\n" +
	"\x15ServeSnapshotsRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\fR\x06hashes\"\x19\n" +
	"\x17ServeChainPointsRequest\"\x88\x01\n" +
	"\x18ServeChainPointsResponse\x120\n" +
	"\x06points\x18\x01 \x03(\v2\x18.nakamoto.p2p.ChainPointR\x06points\x12\x19\n" +
	"\btip_hash\x18\x02 \x01(\fR\atipHash\x12\x1f\n" +
	"\vtip_ordinal\x18\x03 \x01(\x03R\n" +
	"tipOrdinal\"\x94\x02\n" +
	"\x10BackfillSnapshot\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x03R\x04slot\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x03R\aordinal\x12\x1f\n" +
	"\vparent_hash\x18\x04 \x01(\fR\n" +
	"parentHash\x12\x1b\n" +
	"\tvrf_proof\x18\x05 \x01(\fR\bvrfProof\x12$\n" +
	"\x0evrf_public_key\x18\x06 \x01(\fR\fvrfPublicKey\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1f\n" +
	"\vproducer_id\x18\b \x01(\fR\n" +
	"producerId\x12\x1f\n" +
	"\vparent_slot\x18\t \x01(\x03R\n" +
	"parentSlot\"\x81\x01\n" +
	"\x13FetchByRangeRequest\x12#\n" +
	"\rstart_ordinal\x18\x01 \x01(\x03R\fstartOrdinal\x12\x1f\n" +
	"\vend_ordinal\x18\x02 \x01(\x03R\n" +
	"endOrdinal\x12$\n" +
	"\x0etarget_peer_id\x18\x03 \x01(\fR\ftargetPeerId\"\x12\n" +
	"\x10ListPeersRequest\".\n" +
	"\x11ListPeersResponse\x12\x19\n" +
	"\bpeer_ids\x18\x01 \x03(\fR\apeerIds2\xa8\x04\n" +
	"\x0eSidecarService\x12H\n" +
	"\x0fPublishSnapshot\x12\x16.nakamoto.p2p.Snapshot\x1a\x1d.nakamoto.p2p.PublishResponse\x12Q\n" +
	"\x12PublishAttestation\x12\x1c.nakamoto.p2p.TipAttestation\x1a\x1d.nakamoto.p2p.PublishResponse\x12B\n" +
	"\fPublishRumor\x12\x13.nakamoto.p2p.Rumor\x1a\x1d.nakamoto.p2p.PublishResponse\x12V\n" +
	"\x16PublishMetagraphBinary\x12\x1d.nakamoto.p2p.MetagraphBinary\x1a\x1d.nakamoto.p2p.PublishResponse\x12J\n" +
	"\tSubscribe\x12\x1e.nakamoto.p2p.SubscribeRequest\x1a\x1b.nakamoto.p2p.GossipMessage0\x01\x12L\n" +
	"\tPeerCount\x12\x1e.nakamoto.p2p.PeerCountRequest\x1a\x1f.nakamoto.p2p.PeerCountResponse\x12C\n" +
	"\x06Health\x12\x1b.nakamoto.p2p.HealthRequest\x1a\x1c.nakamoto.p2p.HealthResponse2\xb8\x03\n" +
	"\x11ChainSyncOutbound\x12O\n" +
	"\x0eFetchSnapshots\x12#.nakamoto.p2p.FetchSnapshotsRequest\x1a\x16.nakamoto.p2p.Snapshot0\x01\x12S\n" +
	"\fFetchByRange\x12!.nakamoto.p2p.FetchByRangeRequest\x1a\x1e.nakamoto.p2p.BackfillSnapshot0\x01\x12a\n" +
	"\x10FindIntersection\x12%.nakamoto.p2p.FindIntersectionRequest\x1a&.nakamoto.p2p.FindIntersectionResponse\x12L\n" +
	"\n" +
	"GetPeerTip\x12\x1f.nakamoto.p2p.GetPeerTipRequest\x1a\x1d.nakamoto.p2p.PeerTipResponse\x12L\n" +
	"\tListPeers\x12\x1e.nakamoto.p2p.ListPeersRequest\x1a\x1f.nakamoto.p2p.ListPeersResponse2\x9b\x02\n" +
	"\x10ChainSyncInbound\x12O\n" +
	"\x0eServeSnapshots\x12#.nakamoto.p2p.ServeSnapshotsRequest\x1a\x16.nakamoto.p2p.Snapshot0\x01\x12S\n" +
	"\fServeByRange\x12!.nakamoto.p2p.FetchByRangeRequest\x1a\x1e.nakamoto.p2p.BackfillSnapshot0\x01\x12a\n" +
	"\x10ServeChainPoints\x12%.nakamoto.p2p.ServeChainPointsRequest\x1a&.nakamoto.p2p.ServeChainPointsResponseB-Z+github.com/scasplte2/tessellation/p2p/protob\x06proto3"

var (
	file_proto_sidecar_proto_rawDescOnce sync.Once
	file_proto_sidecar_proto_rawDescData []byte
)

func file_proto_sidecar_proto_rawDescGZIP() []byte {
	file_proto_sidecar_proto_rawDescOnce.Do(func() {
		file_proto_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sidecar_proto_rawDesc), len(file_proto_sidecar_proto_rawDesc)))
	})
	return file_proto_sidecar_proto_rawDescData
}

var file_proto_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_sidecar_proto_goTypes = []any{
	(*Snapshot)(nil),                 // 0: nakamoto.p2p.Snapshot
	(*TipAttestation)(nil),           // 1: nakamoto.p2p.TipAttestation
	(*Rumor)(nil),                    // 2: nakamoto.p2p.Rumor
	(*MetagraphBinary)(nil),          // 3: nakamoto.p2p.MetagraphBinary
	(*GossipMessage)(nil),            // 4: nakamoto.p2p.GossipMessage
	(*PublishResponse)(nil),          // 5: nakamoto.p2p.PublishResponse
	(*SubscribeRequest)(nil),         // 6: nakamoto.p2p.SubscribeRequest
	(*PeerCountRequest)(nil),         // 7: nakamoto.p2p.PeerCountRequest
	(*PeerCountResponse)(nil),        // 8: nakamoto.p2p.PeerCountResponse
	(*HealthRequest)(nil),            // 9: nakamoto.p2p.HealthRequest
	(*HealthResponse)(nil),           // 10: nakamoto.p2p.HealthResponse
	(*ChainPoint)(nil),               // 11: nakamoto.p2p.ChainPoint
	(*FetchSnapshotsRequest)(nil),    // 12: nakamoto.p2p.FetchSnapshotsRequest
	(*FindIntersectionRequest)(nil),  // 13: nakamoto.p2p.FindIntersectionRequest
	(*FindIntersectionResponse)(nil), // 14: nakamoto.p2p.FindIntersectionResponse
	(*GetPeerTipRequest)(nil),        // 15: nakamoto.p2p.GetPeerTipRequest
	(*PeerTipResponse)(nil),          // 16: nakamoto.p2p.PeerTipResponse
	(*ServeSnapshotsRequest)(nil),    // 17: nakamoto.p2p.ServeSnapshotsRequest
	(*ServeChainPointsRequest)(nil),  // 18: nakamoto.p2p.ServeChainPointsRequest
	(*ServeChainPointsResponse)(nil), // 19: nakamoto.p2p.ServeChainPointsResponse
	(*BackfillSnapshot)(nil),         // 20: nakamoto.p2p.BackfillSnapshot
	(*FetchByRangeRequest)(nil),      // 21: nakamoto.p2p.FetchByRangeRequest
	(*ListPeersRequest)(nil),         // 22: nakamoto.p2p.ListPeersRequest
	(*ListPeersResponse)(nil),        // 23: nakamoto.p2p.ListPeersResponse
}
var file_proto_sidecar_proto_depIdxs = []int32{
	0,  // 0: nakamoto.p2p.GossipMessage.snapshot:type_name -> nakamoto.p2p.Snapshot
	1,  // 1: nakamoto.p2p.GossipMessage.attestation:type_name -> nakamoto.p2p.TipAttestation
	2,  // 2: nakamoto.p2p.GossipMessage.rumor:type_name -> nakamoto.p2p.Rumor
	3,  // 3: nakamoto.p2p.GossipMessage.metagraph_binary:type_name -> nakamoto.p2p.MetagraphBinary
	11, // 4: nakamoto.p2p.FindIntersectionRequest.points:type_name -> nakamoto.p2p.ChainPoint
	11, // 5: nakamoto.p2p.ServeChainPointsResponse.points:type_name -> nakamoto.p2p.ChainPoint
	0,  // 6: nakamoto.p2p.SidecarService.PublishSnapshot:input_type -> nakamoto.p2p.Snapshot
	1,  // 7: nakamoto.p2p.SidecarService.PublishAttestation:input_type -> nakamoto.p2p.TipAttestation
	2,  // 8: nakamoto.p2p.SidecarService.PublishRumor:input_type -> nakamoto.p2p.Rumor
	3,  // 9: nakamoto.p2p.SidecarService.PublishMetagraphBinary:input_type -> nakamoto.p2p.MetagraphBinary
	6,  // 10: nakamoto.p2p.SidecarService.Subscribe:input_type -> nakamoto.p2p.SubscribeRequest
	7,  // 11: nakamoto.p2p.SidecarService.PeerCount:input_type -> nakamoto.p2p.PeerCountRequest
	9,  // 12: nakamoto.p2p.SidecarService.Health:input_type -> nakamoto.p2p.HealthRequest
	12, // 13: nakamoto.p2p.ChainSyncOutbound.FetchSnapshots:input_type -> nakamoto.p2p.FetchSnapshotsRequest
	21, // 14: nakamoto.p2p.ChainSyncOutbound.FetchByRange:input_type -> nakamoto.p2p.FetchByRangeRequest
	13, // 15: nakamoto.p2p.ChainSyncOutbound.FindIntersection:input_type -> nakamoto.p2p.FindIntersectionRequest
	15, // 16: nakamoto.p2p.ChainSyncOutbound.GetPeerTip:input_type -> nakamoto.p2p.GetPeerTipRequest
	22, // 17: nakamoto.p2p.ChainSyncOutbound.ListPeers:input_type -> nakamoto.p2p.ListPeersRequest
	17, // 18: nakamoto.p2p.ChainSyncInbound.ServeSnapshots:input_type -> nakamoto.p2p.ServeSnapshotsRequest
	21, // 19: nakamoto.p2p.ChainSyncInbound.ServeByRange:input_type -> nakamoto.p2p.FetchByRangeRequest
	18, // 20: nakamoto.p2p.ChainSyncInbound.ServeChainPoints:input_type -> nakamoto.p2p.ServeChainPointsRequest
	5,  // 21: nakamoto.p2p.SidecarService.PublishSnapshot:output_type -> nakamoto.p2p.PublishResponse
	5,  // 22: nakamoto.p2p.SidecarService.PublishAttestation:output_type -> nakamoto.p2p.PublishResponse
	5,  // 23: nakamoto.p2p.SidecarService.PublishRumor:output_type -> nakamoto.p2p.PublishResponse
	5,  // 24: nakamoto.p2p.SidecarService.PublishMetagraphBinary:output_type -> nakamoto.p2p.PublishResponse
	4,  // 25: nakamoto.p2p.SidecarService.Subscribe:output_type -> nakamoto.p2p.GossipMessage
	8,  // 26: nakamoto.p2p.SidecarService.PeerCount:output_type -> nakamoto.p2p.PeerCountResponse
	10, // 27: nakamoto.p2p.SidecarService.Health:output_type -> nakamoto.p2p.HealthResponse
	0,  // 28: nakamoto.p2p.ChainSyncOutbound.FetchSnapshots:output_type -> nakamoto.p2p.Snapshot
	20, // 29: nakamoto.p2p.ChainSyncOutbound.FetchByRange:output_type -> nakamoto.p2p.BackfillSnapshot
	14, // 30: nakamoto.p2p.ChainSyncOutbound.FindIntersection:output_type -> nakamoto.p2p.FindIntersectionResponse
	16, // 31: nakamoto.p2p.ChainSyncOutbound.GetPeerTip:output_type -> nakamoto.p2p.PeerTipResponse
	23, // 32: nakamoto.p2p.ChainSyncOutbound.ListPeers:output_type -> nakamoto.p2p.ListPeersResponse
	0,  // 33: nakamoto.p2p.ChainSyncInbound.ServeSnapshots:output_type -> nakamoto.p2p.Snapshot
	20, // 34: nakamoto.p2p.ChainSyncInbound.ServeByRange:output_type -> nakamoto.p2p.BackfillSnapshot
	19, // 35: nakamoto.p2p.ChainSyncInbound.ServeChainPoints:output_type -> nakamoto.p2p.ServeChainPointsResponse
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_sidecar_proto_init() }
func file_proto_sidecar_proto_init() {
	if File_proto_sidecar_proto != nil {
		return
	}
	file_proto_sidecar_proto_msgTypes[4].OneofWrappers = []any{
		(*GossipMessage_Snapshot)(nil),
		(*GossipMessage_Attestation)(nil),
		(*GossipMessage_Rumor)(nil),
		(*GossipMessage_MetagraphBinary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sidecar_proto_rawDesc), len(file_proto_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_sidecar_proto_goTypes,
		DependencyIndexes: file_proto_sidecar_proto_depIdxs,
		MessageInfos:      file_proto_sidecar_proto_msgTypes,
	}.Build()
	File_proto_sidecar_proto = out.File
	file_proto_sidecar_proto_goTypes = nil
	file_proto_sidecar_proto_depIdxs = nil
}
