// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/sidecar.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SidecarService_PublishSnapshot_FullMethodName                   = "/nakamoto.p2p.SidecarService/PublishSnapshot"
	SidecarService_PublishAttestation_FullMethodName                = "/nakamoto.p2p.SidecarService/PublishAttestation"
	SidecarService_PublishRumor_FullMethodName                      = "/nakamoto.p2p.SidecarService/PublishRumor"
	SidecarService_PublishMetagraphBinary_FullMethodName            = "/nakamoto.p2p.SidecarService/PublishMetagraphBinary"
	SidecarService_PublishMetagraphAttestation_FullMethodName       = "/nakamoto.p2p.SidecarService/PublishMetagraphAttestation"
	SidecarService_PublishAllowSpendBlock_FullMethodName            = "/nakamoto.p2p.SidecarService/PublishAllowSpendBlock"
	SidecarService_PublishDAGBlock_FullMethodName                   = "/nakamoto.p2p.SidecarService/PublishDAGBlock"
	SidecarService_PublishTokenLockBlock_FullMethodName             = "/nakamoto.p2p.SidecarService/PublishTokenLockBlock"
	SidecarService_PublishShardCheckpoint_FullMethodName            = "/nakamoto.p2p.SidecarService/PublishShardCheckpoint"
	SidecarService_PublishShardCheckpointAttestation_FullMethodName = "/nakamoto.p2p.SidecarService/PublishShardCheckpointAttestation"
	SidecarService_PublishFraudProof_FullMethodName                 = "/nakamoto.p2p.SidecarService/PublishFraudProof"
	SidecarService_ConfirmFinalized_FullMethodName                  = "/nakamoto.p2p.SidecarService/ConfirmFinalized"
	SidecarService_Subscribe_FullMethodName                         = "/nakamoto.p2p.SidecarService/Subscribe"
	SidecarService_PeerCount_FullMethodName                         = "/nakamoto.p2p.SidecarService/PeerCount"
	SidecarService_Health_FullMethodName                            = "/nakamoto.p2p.SidecarService/Health"
)

// SidecarServiceClient is the client API for SidecarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The sidecar exposes this service on localhost for the JVM to call.
type SidecarServiceClient interface {
	// Publish a snapshot to the network (JVM won a slot).
	PublishSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish an attestation to the network.
	PublishAttestation(ctx context.Context, in *TipAttestation, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish a generic rumor (event / BFT consensus message / etc).
	PublishRumor(ctx context.Context, in *Rumor, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish a metagraph state channel snapshot binary to all GL0 nodes.
	PublishMetagraphBinary(ctx context.Context, in *MetagraphBinary, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish a per-metagraph committee attestation to all GL0 nodes (Slice S2).
	PublishMetagraphAttestation(ctx context.Context, in *MetagraphAttestation, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish an AllowSpendBlock to all GL0 nodes via the durable outbox path
	// (task #196: replaces the single-peer HTTP POST from Swap.sendBlockToL0).
	PublishAllowSpendBlock(ctx context.Context, in *AllowSpendBlock, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish a DAG block to all GL0 nodes via the durable outbox path. Replaces
	// the single-peer HTTP POST from `StateChannel.sendBlockToL0`. Same durable-
	// outbox machinery as #196 — the sidecar re-publishes on a ticker until the
	// JVM acks Phase-3 finality via `ConfirmFinalized`.
	PublishDAGBlock(ctx context.Context, in *DAGBlock, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish a TokenLockBlock to all GL0 nodes via the durable outbox path.
	// Replaces the single-peer HTTP POST from `TokenLock.sendBlockToL0`. Same
	// durable-outbox machinery as #196 / PublishAllowSpendBlock.
	PublishTokenLockBlock(ctx context.Context, in *TokenLockBlock, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish a raw shard checkpoint to `shard-checkpoint-<shardId>`. The current
	// transitional sidecar eagerly joins every GL0 to every configured shard;
	// target transport must restrict this raw lane to the exact current execution
	// and watchtower assignments. A distinct GL0-wide execution-certified
	// checkpoint/diff lane for ordinary noncommittee adoption is still required
	// and is not implemented by this RPC.
	PublishShardCheckpoint(ctx context.Context, in *ShardCheckpointWire, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish an execution-committee signature by a non-producing member on the
	// per-shard attestation topic. Every signer must independently replay the
	// exact ordered framework inputs and reproduce the checkpoint result before
	// signing. Validity requires the configured distinct `kQuorum`; shard depth or
	// a legacy ceil(2*K_S/3) count cannot substitute for replay signatures.
	PublishShardCheckpointAttestation(ctx context.Context, in *ShardCheckpointAttestationWire, opts ...grpc.CallOption) (*PublishResponse, error)
	// WATCHTOWER: publish a fraud proof on the gl0-wide `fraud-proof` topic. EVERY
	// gl0 receives it and independently re-runs the deterministic verdict over the
	// disputed checkpoint's own bytes (WATCHTOWER-FRAUD-PROOF-DESIGN.md §10.2).
	PublishFraudProof(ctx context.Context, in *FraudProofEnvelopeWire, opts ...grpc.CallOption) (*PublishResponse, error)
	// JVM tells sidecar that the listed message_ids on `topic` reached Phase-3
	// finality. The sidecar drops the corresponding outbox entries; until this
	// call arrives the outbox keeps republishing them periodically. Idempotent
	// — unknown ids are silently ignored. See task #196.
	ConfirmFinalized(ctx context.Context, in *ConfirmFinalizedRequest, opts ...grpc.CallOption) (*ConfirmFinalizedResponse, error)
	// Subscribe to incoming messages from the network. The first response is
	// always GossipMessage.started and later responses are typed deliveries.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GossipMessage], error)
	// Get connected peer count.
	PeerCount(ctx context.Context, in *PeerCountRequest, opts ...grpc.CallOption) (*PeerCountResponse, error)
	// Health check.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type sidecarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarServiceClient(cc grpc.ClientConnInterface) SidecarServiceClient {
	return &sidecarServiceClient{cc}
}

func (c *sidecarServiceClient) PublishSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishAttestation(ctx context.Context, in *TipAttestation, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishRumor(ctx context.Context, in *Rumor, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishRumor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishMetagraphBinary(ctx context.Context, in *MetagraphBinary, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishMetagraphBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishMetagraphAttestation(ctx context.Context, in *MetagraphAttestation, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishMetagraphAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishAllowSpendBlock(ctx context.Context, in *AllowSpendBlock, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishAllowSpendBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishDAGBlock(ctx context.Context, in *DAGBlock, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishDAGBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishTokenLockBlock(ctx context.Context, in *TokenLockBlock, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishTokenLockBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishShardCheckpoint(ctx context.Context, in *ShardCheckpointWire, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishShardCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishShardCheckpointAttestation(ctx context.Context, in *ShardCheckpointAttestationWire, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishShardCheckpointAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) PublishFraudProof(ctx context.Context, in *FraudProofEnvelopeWire, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, SidecarService_PublishFraudProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) ConfirmFinalized(ctx context.Context, in *ConfirmFinalizedRequest, opts ...grpc.CallOption) (*ConfirmFinalizedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmFinalizedResponse)
	err := c.cc.Invoke(ctx, SidecarService_ConfirmFinalized_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GossipMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SidecarService_ServiceDesc.Streams[0], SidecarService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, GossipMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarService_SubscribeClient = grpc.ServerStreamingClient[GossipMessage]

func (c *sidecarServiceClient) PeerCount(ctx context.Context, in *PeerCountRequest, opts ...grpc.CallOption) (*PeerCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerCountResponse)
	err := c.cc.Invoke(ctx, SidecarService_PeerCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SidecarService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SidecarServiceServer is the server API for SidecarService service.
// All implementations must embed UnimplementedSidecarServiceServer
// for forward compatibility.
//
// The sidecar exposes this service on localhost for the JVM to call.
type SidecarServiceServer interface {
	// Publish a snapshot to the network (JVM won a slot).
	PublishSnapshot(context.Context, *Snapshot) (*PublishResponse, error)
	// Publish an attestation to the network.
	PublishAttestation(context.Context, *TipAttestation) (*PublishResponse, error)
	// Publish a generic rumor (event / BFT consensus message / etc).
	PublishRumor(context.Context, *Rumor) (*PublishResponse, error)
	// Publish a metagraph state channel snapshot binary to all GL0 nodes.
	PublishMetagraphBinary(context.Context, *MetagraphBinary) (*PublishResponse, error)
	// Publish a per-metagraph committee attestation to all GL0 nodes (Slice S2).
	PublishMetagraphAttestation(context.Context, *MetagraphAttestation) (*PublishResponse, error)
	// Publish an AllowSpendBlock to all GL0 nodes via the durable outbox path
	// (task #196: replaces the single-peer HTTP POST from Swap.sendBlockToL0).
	PublishAllowSpendBlock(context.Context, *AllowSpendBlock) (*PublishResponse, error)
	// Publish a DAG block to all GL0 nodes via the durable outbox path. Replaces
	// the single-peer HTTP POST from `StateChannel.sendBlockToL0`. Same durable-
	// outbox machinery as #196 — the sidecar re-publishes on a ticker until the
	// JVM acks Phase-3 finality via `ConfirmFinalized`.
	PublishDAGBlock(context.Context, *DAGBlock) (*PublishResponse, error)
	// Publish a TokenLockBlock to all GL0 nodes via the durable outbox path.
	// Replaces the single-peer HTTP POST from `TokenLock.sendBlockToL0`. Same
	// durable-outbox machinery as #196 / PublishAllowSpendBlock.
	PublishTokenLockBlock(context.Context, *TokenLockBlock) (*PublishResponse, error)
	// Publish a raw shard checkpoint to `shard-checkpoint-<shardId>`. The current
	// transitional sidecar eagerly joins every GL0 to every configured shard;
	// target transport must restrict this raw lane to the exact current execution
	// and watchtower assignments. A distinct GL0-wide execution-certified
	// checkpoint/diff lane for ordinary noncommittee adoption is still required
	// and is not implemented by this RPC.
	PublishShardCheckpoint(context.Context, *ShardCheckpointWire) (*PublishResponse, error)
	// Publish an execution-committee signature by a non-producing member on the
	// per-shard attestation topic. Every signer must independently replay the
	// exact ordered framework inputs and reproduce the checkpoint result before
	// signing. Validity requires the configured distinct `kQuorum`; shard depth or
	// a legacy ceil(2*K_S/3) count cannot substitute for replay signatures.
	PublishShardCheckpointAttestation(context.Context, *ShardCheckpointAttestationWire) (*PublishResponse, error)
	// WATCHTOWER: publish a fraud proof on the gl0-wide `fraud-proof` topic. EVERY
	// gl0 receives it and independently re-runs the deterministic verdict over the
	// disputed checkpoint's own bytes (WATCHTOWER-FRAUD-PROOF-DESIGN.md §10.2).
	PublishFraudProof(context.Context, *FraudProofEnvelopeWire) (*PublishResponse, error)
	// JVM tells sidecar that the listed message_ids on `topic` reached Phase-3
	// finality. The sidecar drops the corresponding outbox entries; until this
	// call arrives the outbox keeps republishing them periodically. Idempotent
	// — unknown ids are silently ignored. See task #196.
	ConfirmFinalized(context.Context, *ConfirmFinalizedRequest) (*ConfirmFinalizedResponse, error)
	// Subscribe to incoming messages from the network. The first response is
	// always GossipMessage.started and later responses are typed deliveries.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[GossipMessage]) error
	// Get connected peer count.
	PeerCount(context.Context, *PeerCountRequest) (*PeerCountResponse, error)
	// Health check.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSidecarServiceServer()
}

// UnimplementedSidecarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSidecarServiceServer struct{}

func (UnimplementedSidecarServiceServer) PublishSnapshot(context.Context, *Snapshot) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSnapshot not implemented")
}
func (UnimplementedSidecarServiceServer) PublishAttestation(context.Context, *TipAttestation) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishAttestation not implemented")
}
func (UnimplementedSidecarServiceServer) PublishRumor(context.Context, *Rumor) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishRumor not implemented")
}
func (UnimplementedSidecarServiceServer) PublishMetagraphBinary(context.Context, *MetagraphBinary) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishMetagraphBinary not implemented")
}
func (UnimplementedSidecarServiceServer) PublishMetagraphAttestation(context.Context, *MetagraphAttestation) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishMetagraphAttestation not implemented")
}
func (UnimplementedSidecarServiceServer) PublishAllowSpendBlock(context.Context, *AllowSpendBlock) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishAllowSpendBlock not implemented")
}
func (UnimplementedSidecarServiceServer) PublishDAGBlock(context.Context, *DAGBlock) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishDAGBlock not implemented")
}
func (UnimplementedSidecarServiceServer) PublishTokenLockBlock(context.Context, *TokenLockBlock) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTokenLockBlock not implemented")
}
func (UnimplementedSidecarServiceServer) PublishShardCheckpoint(context.Context, *ShardCheckpointWire) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishShardCheckpoint not implemented")
}
func (UnimplementedSidecarServiceServer) PublishShardCheckpointAttestation(context.Context, *ShardCheckpointAttestationWire) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishShardCheckpointAttestation not implemented")
}
func (UnimplementedSidecarServiceServer) PublishFraudProof(context.Context, *FraudProofEnvelopeWire) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishFraudProof not implemented")
}
func (UnimplementedSidecarServiceServer) ConfirmFinalized(context.Context, *ConfirmFinalizedRequest) (*ConfirmFinalizedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmFinalized not implemented")
}
func (UnimplementedSidecarServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[GossipMessage]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSidecarServiceServer) PeerCount(context.Context, *PeerCountRequest) (*PeerCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PeerCount not implemented")
}
func (UnimplementedSidecarServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSidecarServiceServer) mustEmbedUnimplementedSidecarServiceServer() {}
func (UnimplementedSidecarServiceServer) testEmbeddedByValue()                        {}

// UnsafeSidecarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidecarServiceServer will
// result in compilation errors.
type UnsafeSidecarServiceServer interface {
	mustEmbedUnimplementedSidecarServiceServer()
}

func RegisterSidecarServiceServer(s grpc.ServiceRegistrar, srv SidecarServiceServer) {
	// If the following call panics, it indicates UnimplementedSidecarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SidecarService_ServiceDesc, srv)
}

func _SidecarService_PublishSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishSnapshot(ctx, req.(*Snapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TipAttestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishAttestation(ctx, req.(*TipAttestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishRumor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rumor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishRumor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishRumor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishRumor(ctx, req.(*Rumor))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishMetagraphBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetagraphBinary)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishMetagraphBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishMetagraphBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishMetagraphBinary(ctx, req.(*MetagraphBinary))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishMetagraphAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetagraphAttestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishMetagraphAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishMetagraphAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishMetagraphAttestation(ctx, req.(*MetagraphAttestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishAllowSpendBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowSpendBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishAllowSpendBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishAllowSpendBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishAllowSpendBlock(ctx, req.(*AllowSpendBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishDAGBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DAGBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishDAGBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishDAGBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishDAGBlock(ctx, req.(*DAGBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishTokenLockBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenLockBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishTokenLockBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishTokenLockBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishTokenLockBlock(ctx, req.(*TokenLockBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishShardCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardCheckpointWire)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishShardCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishShardCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishShardCheckpoint(ctx, req.(*ShardCheckpointWire))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishShardCheckpointAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardCheckpointAttestationWire)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishShardCheckpointAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishShardCheckpointAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishShardCheckpointAttestation(ctx, req.(*ShardCheckpointAttestationWire))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_PublishFraudProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FraudProofEnvelopeWire)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PublishFraudProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PublishFraudProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PublishFraudProof(ctx, req.(*FraudProofEnvelopeWire))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_ConfirmFinalized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmFinalizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).ConfirmFinalized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_ConfirmFinalized_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).ConfirmFinalized(ctx, req.(*ConfirmFinalizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SidecarServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, GossipMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarService_SubscribeServer = grpc.ServerStreamingServer[GossipMessage]

func _SidecarService_PeerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).PeerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_PeerCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).PeerCount(ctx, req.(*PeerCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SidecarService_ServiceDesc is the grpc.ServiceDesc for SidecarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SidecarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nakamoto.p2p.SidecarService",
	HandlerType: (*SidecarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishSnapshot",
			Handler:    _SidecarService_PublishSnapshot_Handler,
		},
		{
			MethodName: "PublishAttestation",
			Handler:    _SidecarService_PublishAttestation_Handler,
		},
		{
			MethodName: "PublishRumor",
			Handler:    _SidecarService_PublishRumor_Handler,
		},
		{
			MethodName: "PublishMetagraphBinary",
			Handler:    _SidecarService_PublishMetagraphBinary_Handler,
		},
		{
			MethodName: "PublishMetagraphAttestation",
			Handler:    _SidecarService_PublishMetagraphAttestation_Handler,
		},
		{
			MethodName: "PublishAllowSpendBlock",
			Handler:    _SidecarService_PublishAllowSpendBlock_Handler,
		},
		{
			MethodName: "PublishDAGBlock",
			Handler:    _SidecarService_PublishDAGBlock_Handler,
		},
		{
			MethodName: "PublishTokenLockBlock",
			Handler:    _SidecarService_PublishTokenLockBlock_Handler,
		},
		{
			MethodName: "PublishShardCheckpoint",
			Handler:    _SidecarService_PublishShardCheckpoint_Handler,
		},
		{
			MethodName: "PublishShardCheckpointAttestation",
			Handler:    _SidecarService_PublishShardCheckpointAttestation_Handler,
		},
		{
			MethodName: "PublishFraudProof",
			Handler:    _SidecarService_PublishFraudProof_Handler,
		},
		{
			MethodName: "ConfirmFinalized",
			Handler:    _SidecarService_ConfirmFinalized_Handler,
		},
		{
			MethodName: "PeerCount",
			Handler:    _SidecarService_PeerCount_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SidecarService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SidecarService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sidecar.proto",
}

const (
	ChainSyncOutbound_FetchSnapshots_FullMethodName         = "/nakamoto.p2p.ChainSyncOutbound/FetchSnapshots"
	ChainSyncOutbound_FindIntersection_FullMethodName       = "/nakamoto.p2p.ChainSyncOutbound/FindIntersection"
	ChainSyncOutbound_GetPeerTip_FullMethodName             = "/nakamoto.p2p.ChainSyncOutbound/GetPeerTip"
	ChainSyncOutbound_FetchMetagraphBinaries_FullMethodName = "/nakamoto.p2p.ChainSyncOutbound/FetchMetagraphBinaries"
)

// ChainSyncOutboundClient is the client API for ChainSyncOutbound service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JVM → Sidecar: request chain data from the network.
// The sidecar picks a peer, opens a libp2p stream, relays the request,
// and streams the response back to the JVM.
type ChainSyncOutboundClient interface {
	FetchSnapshots(ctx context.Context, in *FetchSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error)
	FindIntersection(ctx context.Context, in *FindIntersectionRequest, opts ...grpc.CallOption) (*FindIntersectionResponse, error)
	GetPeerTip(ctx context.Context, in *GetPeerTipRequest, opts ...grpc.CallOption) (*PeerTipResponse, error)
	// #259: pull missing metagraph binaries by value-hash from a peer.
	FetchMetagraphBinaries(ctx context.Context, in *FetchMetagraphBinariesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetagraphBinaryResponse], error)
}

type chainSyncOutboundClient struct {
	cc grpc.ClientConnInterface
}

func NewChainSyncOutboundClient(cc grpc.ClientConnInterface) ChainSyncOutboundClient {
	return &chainSyncOutboundClient{cc}
}

func (c *chainSyncOutboundClient) FetchSnapshots(ctx context.Context, in *FetchSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChainSyncOutbound_ServiceDesc.Streams[0], ChainSyncOutbound_FetchSnapshots_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchSnapshotsRequest, Snapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainSyncOutbound_FetchSnapshotsClient = grpc.ServerStreamingClient[Snapshot]

func (c *chainSyncOutboundClient) FindIntersection(ctx context.Context, in *FindIntersectionRequest, opts ...grpc.CallOption) (*FindIntersectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindIntersectionResponse)
	err := c.cc.Invoke(ctx, ChainSyncOutbound_FindIntersection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainSyncOutboundClient) GetPeerTip(ctx context.Context, in *GetPeerTipRequest, opts ...grpc.CallOption) (*PeerTipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerTipResponse)
	err := c.cc.Invoke(ctx, ChainSyncOutbound_GetPeerTip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainSyncOutboundClient) FetchMetagraphBinaries(ctx context.Context, in *FetchMetagraphBinariesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetagraphBinaryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChainSyncOutbound_ServiceDesc.Streams[1], ChainSyncOutbound_FetchMetagraphBinaries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchMetagraphBinariesRequest, MetagraphBinaryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainSyncOutbound_FetchMetagraphBinariesClient = grpc.ServerStreamingClient[MetagraphBinaryResponse]

// ChainSyncOutboundServer is the server API for ChainSyncOutbound service.
// All implementations must embed UnimplementedChainSyncOutboundServer
// for forward compatibility.
//
// JVM → Sidecar: request chain data from the network.
// The sidecar picks a peer, opens a libp2p stream, relays the request,
// and streams the response back to the JVM.
type ChainSyncOutboundServer interface {
	FetchSnapshots(*FetchSnapshotsRequest, grpc.ServerStreamingServer[Snapshot]) error
	FindIntersection(context.Context, *FindIntersectionRequest) (*FindIntersectionResponse, error)
	GetPeerTip(context.Context, *GetPeerTipRequest) (*PeerTipResponse, error)
	// #259: pull missing metagraph binaries by value-hash from a peer.
	FetchMetagraphBinaries(*FetchMetagraphBinariesRequest, grpc.ServerStreamingServer[MetagraphBinaryResponse]) error
	mustEmbedUnimplementedChainSyncOutboundServer()
}

// UnimplementedChainSyncOutboundServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainSyncOutboundServer struct{}

func (UnimplementedChainSyncOutboundServer) FetchSnapshots(*FetchSnapshotsRequest, grpc.ServerStreamingServer[Snapshot]) error {
	return status.Error(codes.Unimplemented, "method FetchSnapshots not implemented")
}
func (UnimplementedChainSyncOutboundServer) FindIntersection(context.Context, *FindIntersectionRequest) (*FindIntersectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindIntersection not implemented")
}
func (UnimplementedChainSyncOutboundServer) GetPeerTip(context.Context, *GetPeerTipRequest) (*PeerTipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeerTip not implemented")
}
func (UnimplementedChainSyncOutboundServer) FetchMetagraphBinaries(*FetchMetagraphBinariesRequest, grpc.ServerStreamingServer[MetagraphBinaryResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchMetagraphBinaries not implemented")
}
func (UnimplementedChainSyncOutboundServer) mustEmbedUnimplementedChainSyncOutboundServer() {}
func (UnimplementedChainSyncOutboundServer) testEmbeddedByValue()                           {}

// UnsafeChainSyncOutboundServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainSyncOutboundServer will
// result in compilation errors.
type UnsafeChainSyncOutboundServer interface {
	mustEmbedUnimplementedChainSyncOutboundServer()
}

func RegisterChainSyncOutboundServer(s grpc.ServiceRegistrar, srv ChainSyncOutboundServer) {
	// If the following call panics, it indicates UnimplementedChainSyncOutboundServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChainSyncOutbound_ServiceDesc, srv)
}

func _ChainSyncOutbound_FetchSnapshots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchSnapshotsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChainSyncOutboundServer).FetchSnapshots(m, &grpc.GenericServerStream[FetchSnapshotsRequest, Snapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainSyncOutbound_FetchSnapshotsServer = grpc.ServerStreamingServer[Snapshot]

func _ChainSyncOutbound_FindIntersection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindIntersectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainSyncOutboundServer).FindIntersection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainSyncOutbound_FindIntersection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainSyncOutboundServer).FindIntersection(ctx, req.(*FindIntersectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainSyncOutbound_GetPeerTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerTipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainSyncOutboundServer).GetPeerTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainSyncOutbound_GetPeerTip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainSyncOutboundServer).GetPeerTip(ctx, req.(*GetPeerTipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainSyncOutbound_FetchMetagraphBinaries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchMetagraphBinariesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChainSyncOutboundServer).FetchMetagraphBinaries(m, &grpc.GenericServerStream[FetchMetagraphBinariesRequest, MetagraphBinaryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainSyncOutbound_FetchMetagraphBinariesServer = grpc.ServerStreamingServer[MetagraphBinaryResponse]

// ChainSyncOutbound_ServiceDesc is the grpc.ServiceDesc for ChainSyncOutbound service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainSyncOutbound_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nakamoto.p2p.ChainSyncOutbound",
	HandlerType: (*ChainSyncOutboundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindIntersection",
			Handler:    _ChainSyncOutbound_FindIntersection_Handler,
		},
		{
			MethodName: "GetPeerTip",
			Handler:    _ChainSyncOutbound_GetPeerTip_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchSnapshots",
			Handler:       _ChainSyncOutbound_FetchSnapshots_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchMetagraphBinaries",
			Handler:       _ChainSyncOutbound_FetchMetagraphBinaries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sidecar.proto",
}

const (
	ChainSyncInbound_ServeSnapshots_FullMethodName         = "/nakamoto.p2p.ChainSyncInbound/ServeSnapshots"
	ChainSyncInbound_ServeChainPoints_FullMethodName       = "/nakamoto.p2p.ChainSyncInbound/ServeChainPoints"
	ChainSyncInbound_ServeMetagraphBinaries_FullMethodName = "/nakamoto.p2p.ChainSyncInbound/ServeMetagraphBinaries"
)

// ChainSyncInboundClient is the client API for ChainSyncInbound service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sidecar → JVM: serve local chain data to incoming network requests.
// When a peer asks our sidecar for snapshots, the sidecar calls these
// methods on the JVM to fulfill the request.
type ChainSyncInboundClient interface {
	ServeSnapshots(ctx context.Context, in *ServeSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error)
	ServeChainPoints(ctx context.Context, in *ServeChainPointsRequest, opts ...grpc.CallOption) (*ServeChainPointsResponse, error)
	// #259: serve local metagraph binaries (recent-finalized snapshots +
	// non-destructive orphan-buffer peek) to an incoming network request.
	ServeMetagraphBinaries(ctx context.Context, in *FetchMetagraphBinariesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetagraphBinaryResponse], error)
}

type chainSyncInboundClient struct {
	cc grpc.ClientConnInterface
}

func NewChainSyncInboundClient(cc grpc.ClientConnInterface) ChainSyncInboundClient {
	return &chainSyncInboundClient{cc}
}

func (c *chainSyncInboundClient) ServeSnapshots(ctx context.Context, in *ServeSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Snapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChainSyncInbound_ServiceDesc.Streams[0], ChainSyncInbound_ServeSnapshots_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServeSnapshotsRequest, Snapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainSyncInbound_ServeSnapshotsClient = grpc.ServerStreamingClient[Snapshot]

func (c *chainSyncInboundClient) ServeChainPoints(ctx context.Context, in *ServeChainPointsRequest, opts ...grpc.CallOption) (*ServeChainPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServeChainPointsResponse)
	err := c.cc.Invoke(ctx, ChainSyncInbound_ServeChainPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainSyncInboundClient) ServeMetagraphBinaries(ctx context.Context, in *FetchMetagraphBinariesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetagraphBinaryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChainSyncInbound_ServiceDesc.Streams[1], ChainSyncInbound_ServeMetagraphBinaries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchMetagraphBinariesRequest, MetagraphBinaryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainSyncInbound_ServeMetagraphBinariesClient = grpc.ServerStreamingClient[MetagraphBinaryResponse]

// ChainSyncInboundServer is the server API for ChainSyncInbound service.
// All implementations must embed UnimplementedChainSyncInboundServer
// for forward compatibility.
//
// Sidecar → JVM: serve local chain data to incoming network requests.
// When a peer asks our sidecar for snapshots, the sidecar calls these
// methods on the JVM to fulfill the request.
type ChainSyncInboundServer interface {
	ServeSnapshots(*ServeSnapshotsRequest, grpc.ServerStreamingServer[Snapshot]) error
	ServeChainPoints(context.Context, *ServeChainPointsRequest) (*ServeChainPointsResponse, error)
	// #259: serve local metagraph binaries (recent-finalized snapshots +
	// non-destructive orphan-buffer peek) to an incoming network request.
	ServeMetagraphBinaries(*FetchMetagraphBinariesRequest, grpc.ServerStreamingServer[MetagraphBinaryResponse]) error
	mustEmbedUnimplementedChainSyncInboundServer()
}

// UnimplementedChainSyncInboundServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainSyncInboundServer struct{}

func (UnimplementedChainSyncInboundServer) ServeSnapshots(*ServeSnapshotsRequest, grpc.ServerStreamingServer[Snapshot]) error {
	return status.Error(codes.Unimplemented, "method ServeSnapshots not implemented")
}
func (UnimplementedChainSyncInboundServer) ServeChainPoints(context.Context, *ServeChainPointsRequest) (*ServeChainPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServeChainPoints not implemented")
}
func (UnimplementedChainSyncInboundServer) ServeMetagraphBinaries(*FetchMetagraphBinariesRequest, grpc.ServerStreamingServer[MetagraphBinaryResponse]) error {
	return status.Error(codes.Unimplemented, "method ServeMetagraphBinaries not implemented")
}
func (UnimplementedChainSyncInboundServer) mustEmbedUnimplementedChainSyncInboundServer() {}
func (UnimplementedChainSyncInboundServer) testEmbeddedByValue()                          {}

// UnsafeChainSyncInboundServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainSyncInboundServer will
// result in compilation errors.
type UnsafeChainSyncInboundServer interface {
	mustEmbedUnimplementedChainSyncInboundServer()
}

func RegisterChainSyncInboundServer(s grpc.ServiceRegistrar, srv ChainSyncInboundServer) {
	// If the following call panics, it indicates UnimplementedChainSyncInboundServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChainSyncInbound_ServiceDesc, srv)
}

func _ChainSyncInbound_ServeSnapshots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServeSnapshotsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChainSyncInboundServer).ServeSnapshots(m, &grpc.GenericServerStream[ServeSnapshotsRequest, Snapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainSyncInbound_ServeSnapshotsServer = grpc.ServerStreamingServer[Snapshot]

func _ChainSyncInbound_ServeChainPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeChainPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainSyncInboundServer).ServeChainPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainSyncInbound_ServeChainPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainSyncInboundServer).ServeChainPoints(ctx, req.(*ServeChainPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainSyncInbound_ServeMetagraphBinaries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchMetagraphBinariesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChainSyncInboundServer).ServeMetagraphBinaries(m, &grpc.GenericServerStream[FetchMetagraphBinariesRequest, MetagraphBinaryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChainSyncInbound_ServeMetagraphBinariesServer = grpc.ServerStreamingServer[MetagraphBinaryResponse]

// ChainSyncInbound_ServiceDesc is the grpc.ServiceDesc for ChainSyncInbound service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainSyncInbound_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nakamoto.p2p.ChainSyncInbound",
	HandlerType: (*ChainSyncInboundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServeChainPoints",
			Handler:    _ChainSyncInbound_ServeChainPoints_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServeSnapshots",
			Handler:       _ChainSyncInbound_ServeSnapshots_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ServeMetagraphBinaries",
			Handler:       _ChainSyncInbound_ServeMetagraphBinaries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sidecar.proto",
}
